go-kratos/kratos

- pkg/net/http/blademaster/trace.go
fixed spelling error: blademaster/trace.go
NewTraceTracesport -> NewTraceTransport
> fix spelling error

- pkg/ratelimit/bbr/bbr.go
防止cpustat.ReadStat(...)在panic的情况下ticker没有被Stop，然后又创建了新的ticker.
> avoid ticker leak when cpustat.ReadStat(...) panic

- pkg/ratelimit/bbr/bbr.go
- pkg/ratelimit/bbr/bbr_test.go
修复 prev_drop 变量非线程安全的问题 ：
```
(dev_py3) ➜  bbr git:(master) go test -race -test.v -test.run ./
=== RUN   TestBBR
==================
WARNING: DATA RACE
Write at 0x00c00023e2e0 by goroutine 56:
go-common/library/rate/limit/bbr.(*BBR).Allow()
/Users/chengfei/Dropbox/workspace/golang/src/go-common/library/rate/limit/bbr/bbr.go:157 +0x110
go-common/library/rate/limit/bbr.TestBBR.func1()
/Users/chengfei/Dropbox/workspace/golang/src/go-common/library/rate/limit/bbr/bbr_test.go:33 +0xc4
Previous write at 0x00c00023e2e0 by goroutine 33:
go-common/library/rate/limit/bbr.(*BBR).Allow()
/Users/chengfei/Dropbox/workspace/golang/src/go-common/library/rate/limit/bbr/bbr.go:157 +0x110
go-common/library/rate/limit/bbr.TestBBR.func1()
/Users/chengfei/Dropbox/workspace/golang/src/go-common/library/rate/limit …
```
> make pre-drop thread-safe in bbr

- tool/kratos/main.go
- tool/kratos/new.go
- tool/kratos/project.go
- tool/kratos/template.go
feat: 
1. 创建项目如果带有proto参数，在api目录放置一个go generate
2. 创建项目支持 -m 参数，可以自定义 go mod init 时作为参数的 module name，
2.1 module name 规则：有指定 module name时使用指定的输入，否则尝试使用 path.Join(Owner, Name)
2.2 相关的 tpl 里所有import 语句，将{{.Name}}替换成 {{.ModuleName}}
> feat: 创建项目支持 -m 参数，可以自定义 go mod init 时作为参数的 module name

- pkg/ratelimit/bbr/bbr.go
- pkg/ratelimit/bbr/bbr_test.go
背景
自适应限流在 cpu 抖动后，可能造成限流过激。
触发场景：
1. cpu 抖动
2. 接口流量稳定不变
3. 接口并发随机
> 修复自适应限流在 cpu 抖动后，可能出现限流过激的问题

- pkg/cache/redis/pool.go
自定义的 option 需要支持覆盖任何默认的 option，所以参数中的 options 要放到后面，不然会出现无法覆盖的情况，比如，使用 DialNetDial() 无法覆盖 DialConnectTimeout()
> fix redis option order

- pkg/ratelimit/bbr/bbr.go
- pkg/ratelimit/bbr/bbr_test.go
- pkg/stat/metric/rolling_counter.go
1. rtStat 使用 rolling counter
2. preDrop 使用 atomic.Value 以利用 monotonic time
3. 修改 hotpath，减少 cpu 计算
4. rollingCounter，当前采样点不纳入统计中
5. 缓存 maxPass & minRt，检查计算
6. prevDrop 使用 duration，以利用 monotonic time
优化前：
``` bash
BenchmarkBBRAllowUnderLowLoad-8         	  200000	     30084 ns/op
BenchmarkBBRAllowUnderHighLoad-8        	  200000	     30315 ns/op
BenchmarkBBRShouldDropUnderLowLoad-8    	 2000000	       572 ns/op
BenchmarkBBRShouldDropUnderHighLoad-8   	 2000000	       570 ns/op
```
优化后：
~~BenchmarkBBRAllowUnderLowLoad-8         	 3000000	       465 ns/op
BenchmarkBBRAllowUnderHighLoad-8        	 3000000	       468 ns/op
BenchmarkBBRShouldDropUnderLowLoad-8    	200000000	         6.35 ns/op
BenchmarkBBRShouldDropUnderHighLoad-8   	200000000	         6.86 ns/op~~
``` bash …
```
> perfermance:  reduce calculation times of maxInflight

- pkg/net/http/blademaster/metadata.go
When using `strings.TrimLef`, prefix that contains character in cutset will be cut. Should use `strings.TrimPrefix` instead.
> Fix trim prefix in bm metadata parsing

- tool/protobuf/protoc-gen-bswagger/generator.go
```
rpc methoda(Empty) returns (Empty) {
option (google.api.http) = {
post:"/same/path"
};
};
rpc methodb(Empty) returns (Empty) {
option (google.api.http) = {
get:"/same/path"
};
};
```
proto2swagger support same path different method
> fix: proto2swagger support same path different method (close #191)

- tool/kratos/template.go
- tool/kratos/version.go
v0.2.1
Added:
1、prometheus监控模版化；
2、warden grpc默认注册direct协议；
Fixed:
1、修复discovery每隔30s进行switch node；
2、修复ectd package引入不对；
3、去除go mod replace，解决可能会出现编译失败；
> update kratos version

- tool/kratos/template.go
- tool/kratos/version.go
v0.2.2
Added:
1、添加doc和example用例文档；
2、添加ecode proto生成工具；
3、添加prometheus dashboards监控统计模板；
4、bm generator支持默认grpc path生成；
Fixed:
1、修复BM注册404、405 handle；
2、修复warden resolver集群过虑bug；
3、修复DB trace的ip信息；
4、修复获取网卡IP对状态判断；
5、修复zipkin trace信息不完整；
> update kratos to v0.2.2

- pkg/net/http/blademaster/logger.go
按照`quickstart`运行时，发现如果请求一个路由中不存在的地址，`goroutine` 中会报 `panic`，如图：
追踪后发现，是`logger`中间件中处理字符串切片时，缺少一个字符串为空的条件判断。正常注册的路由 `c.RoutePath` 不会为空，但是通过诸如 `engine.NoRoute(),engine.NoMethod()`等方式注册的 `handler`中， `c.RoutePath` 是空字符串
> protect slice bounds not out of range

- tool/kratos-protoc/protoc.go
- tool/kratos/tool.go
您好，感谢在issues#344的邀请，我提交了这个pr。
原因如issues#344中描述，windows中gopath用分号隔开，我照着tool/kratos-protoc/protoc.go中的checkProtoc()方法里面的内容改了一下，"windows"字符串从tool\kratos\tool_index.go中取得。
测试以后在windows中能够运行。解决了我在issues#344中的问题。
我还在tool/kratos/tool.go中找到相同的gopath获取方式，也一起改了，但不知道对windows有什么影响。
再次感谢您的邀请。
> gopath compatible with windows

- pkg/net/rpc/warden/server_test.go
more requests, increase breaker being triggered probability
> Fix warden ut

- pkg/conf/paladin/file.go
由于 pkg/conf/paladin/file.go Line: 165 使用了ioutil.ReadDir来读取目录下文件，而底层使用的是LStat，所以遇到目录的软链接会导致 Line: 170 的 file.IsDir()为false，所以加个判断
fix #355
> 解决k8s configmap生成的 ..data 软链接目录被识别成文件的问题

- pkg/stat/metric/rolling_policy.go
- pkg/stat/metric/rolling_policy_test.go
There would be a problem if update the lastAppendTime to time.Now() after a token was filled into a bucket. Specifically, assuming the bucket duration is 300ms, if I call the MarkSuccess at 400ms and 601ms, what we expect is that the second and third bucket will be filled with one token respectively, however, there will be two tokens filled into the second bucket.  
Following is my test code:  
```go
package kratos
import (
"github.com/bilibili/kratos/pkg/net/netutil/breaker"
"testing"
"time"
)
func TestBreaker(t *testing.T) {
brkGroup := breaker.NewGroup(&breaker.Config{})
brk := brkGroup.Get("name")
time.Sleep(400 * time.Millisecond)
brk.MarkSuccess()
time.Sleep(201 * time.Millisecond)
brk.MarkSuccess()
}
```
Print the bucket points after each MarkSuccess:  
```go
func (r …
```
> opt last append time of rolling policy

- pkg/net/http/blademaster/server.go
server Start method, using errors.Wrapf without return the error
> fix: server start error return

- tool/kratos/tool.go
windows下每次使用tool都会重新使用go get来重新安装，且kratos tool无法识别到已安装的tool。
原因是判断tool是否安装是根据文件是否存在来判断的，但是windows下bin目录的可执行文件是.exe结尾的。。。
https://github.com/bilibili/kratos/blob/7c946dc919c172276e8dbfa706c969ff7033aead/tool/kratos/tool.go#L189-L192
https://github.com/bilibili/kratos/blob/7c946dc919c172276e8dbfa706c969ff7033aead/tool/kratos/tool.go#L177-L187
> 修复windows下无法识别到已安装的tool且每次使用tool都会重新安装

- pkg/net/http/blademaster/server.go
url.RawPath isn't a valid escaping of u.Path.
according official comment:
In general, code should call EscapedPath instead of reading u.RawPath directly.
see more details:
https://stackoverflow.com/questions/39270633/why-does-url-parse-not-populate-url-rawpath
> fix url rawPath

- pkg/net/rpc/warden/validate.go
使用 kratos 定义的错误码会返回 -400 UNKNOWN，无法反馈错误信息
改为 grpc 规范实现
> validate 使用 grpc 标准异常处理

- .github/workflows/go.yml
构建文件中我删除了`docker-compose`下载安装的代码. 因为工作流里好像没用过这个东西... 如果要使用容器, 我建议使用`services.*`来启动.
新的工作流能比以前节省出1分钟以上的构建时间.
> CI: Enhance Build efficiency and functionality.

- tool/kratos-gen-project/new.go
windows 下 modPrefix 错误，以 \ 连接，导致 wndows 下创建服务时，-d 的参数只能是一层目录，不能成功创建如 app/admin 的多层目录
> fix modPrefix error in windows

- pkg/net/http/blademaster/metadata.go
go版本
```
go version go1.13.15 darwin/amd64
```
Mac本地环境下测试kratos-demo，日志打印ip为`ip=[`，原因是本地`RemoteAddr `为`[::1]:54905`，原写法无法支持IPv6地址解析，故此处使用`net.SplitHostPort`以正确解析ip
> get remote ip by SplitHostPort

- tool/kratos/version.go
由于v0.6.0已发布，因此需要更新kratos工具版本。BuildTime 采用的是 release 时间
> Update tool version

- pkg/container/queue/aqm/codel.go
- pkg/container/queue/aqm/codel_test.go
在目前codel实现中，没有放行任何流量。因此小于队列的2048条流量就会被阻塞到超时。超过这个数量的会被直接拒绝。
在查看相关资料后修改为：
增加并发数量配置，以放行流量，当请求完成后会回调pop更新状态计算，同时更新请求的实际并发，并且放行或者拒绝流量。当前这种机制下会根据实际情况来拒绝流量。而在之前的实现里不会接受任何请求。
> fix codel to accept request add config outstanding

- pkg/stat/metric/rolling_counter.go
执行bbr测试的时候，开启data race检测。发现存在并发数据竞争。经过排查是此处读取没有加读锁。
```
$ go test -run TestBBR -race
==================
WARNING: DATA RACE
Write at 0x00c00008ead8 by goroutine 72:
github.com/go-kratos/kratos/pkg/stat/metric.(*RollingPolicy).add()
/Users/zc/Desktop/companyWorkspace/bifrost/learn_proj/kratos/pkg/stat/metric/rolling_policy.go:51 +0x1eb
github.com/go-kratos/kratos/pkg/stat/metric.(*RollingPolicy).Add()
/Users/zc/Desktop/companyWorkspace/bifrost/learn_proj/kratos/pkg/stat/metric/rolling_policy.go:84 +0x84
github.com/go-kratos/kratos/pkg/stat/metric.(*rollingCounter).Add()
/Users/zc/Desktop/companyWorkspace/bifrost/learn_proj/kratos/pkg/stat/metric/rolling_counter.go:44 +0x6c
github.com/go-kratos/kratos/pkg/ratelimit/bbr.(*BBR).Allow.func1() …
```
> fix:fix data race in rolling_counter

- middleware/status/status.go
should not swallow the user's native error information.
Signed-off-by: storyicon <storyicon@foxmail.com>
> display error messages

- transport/http/server.go
1. modify HanldePrefix to HandlePrefix in transport/http/server.go
> fix(http): fix typo in transport/http

- transport/grpc/client.go
- transport/grpc/server.go
- transport/http/client.go
- transport/http/server.go
- transport/transport.go
There are many reasons why strong type should be used here, but only one reason that is closest to the user is described here:
The user obtains the protocol information through `transport.FromContext`, but the definition of `Transport` is as follows:
```
type Transport struct {
Kind string
}
```
If users don’t look at the source code, they don’t know how kratos assigns a value to `Kind`. It might be：
```
grpc, gRPC, GRPC, http, HTTP
```
This makes the `Kind` field difficult to use.
Signed-off-by: storyicon <storyicon@foxmail.com>
> set transport.kind to be strong type

- cmd/kratos/internal/proto/client/client.go
Always print error here. 
```
go get -u github.com/go-kratos/kratos/cmd/kratos/v2
go: downloading github.com/go-kratos/kratos/cmd/kratos/v2 v2.0.0-20210412154310-d92c1edc2668
go get: added github.com/go-git/go-git/v5 v5.3.0
go get: added github.com/go-kratos/kratos/cmd/kratos/v2 v2.0.0-20210412154310-d92c1edc2668
go get: added github.com/kevinburke/ssh_config v1.1.0
go get: added github.com/sergi/go-diff v1.2.0
go get: added github.com/spf13/cobra v1.1.3
go get: upgraded golang.org/x/mod v0.3.0 => v0.4.2
go get -u github.com/go-kratos/kratos/cmd/protoc-gen-go-http/v2
go: downloading github.com/go-kratos/kratos/cmd/protoc-gen-go-http/v2 v2.0.0-20210412154310-d92c1edc2668
go get: added github.com/go-kratos/kratos/cmd/protoc-gen-go-http/v2 v2.0.0-20210412154310-d92c1edc2668
go get -u …
```
> proto/client: print correct err

- cmd/kratos/internal/proto/add/add.go
- cmd/kratos/internal/proto/add/proto.go
1. The function name unexport is inconsistent with the actual behavior, it is more appropriate to name it as export here.
2. *Proto execute() return ([]byte, error), it is already of type []byte, so the conversion here is useless .
> proto/add:  rename to export && remove unnecessary type conversion

- transport/grpc/resolver/discovery/resolver.go
when scheme don't  match grpc, endpoint is ""
> resolver/discovery: fix endpoint, scheme don't  match grpc

- cmd/kratos/internal/base/repo.go
Fix https://github.com/go-kratos/kratos/issues/827
The old way: ~/.kratos/repo/layout-name
The new way: ~/.kratos/host/user/layout-name
> cmd: use structured path save layout

- transport/grpc/client.go
The direct resolver register itself during `init`.
Import the package so that the direct resolver can be initialized when using grpc client.
> Import direct resovler for grpc client

- cmd/kratos/internal/proto/server/template.go
`
kratos proto server api/helloworld/helloworld.proto -t internal/service
`
生成出来的service文件中NewXxxxSerivce返回类型不正确
> fix incorrect return type in service template

- cmd/kratos/internal/proto/client/client.go
fix kratos proto client cmd when the validate.proto is annotated not to generate validate pb file
修复kratos命令，validate.proto 引入，注释未使用时，不生成 validate pb文件
> fix(cmd):  fix kratos cmd

- cmd/kratos/internal/proto/client/client.go
eg:
- api/basedata/tag/v1/tag.proto
- api/basedata/article/v1/article.proto
当 **api/basedata/article/v1/article.proto** import "api/basedata/tag/v1/tag.proto"
时 ，生成的依赖为api/basedata/tag/v1/tag.proto 但是 api/basedata/tag/v1/tag.proto 生成的文件source是tag.proto导致了依赖未找到
现在改成相对路径生成
> fixed:修复了，在默认项目根目录为根路径的情况下跨文件引入proto 由于文件名不全，导致protobuf加载文件not found的bug

- cmd/kratos/internal/project/project.go
- cmd/kratos/internal/proto/server/server.go
cobra will add two hyphens before the flag name by default. If the flag itself has hyphens, three hyphens will appear in the actual output.
> [FIX]the flag name, remove redundant hyphen

- examples/blog/cmd/blog/main.go
rename config to cfg in blog #1117
> fix(examples): rename config to cfg in blog #1117

- config/value.go
- config/value_test.go
When the variable type is `int`/`int32`, I think we can also try to convert it to the desired type, as the `int` is sometimes the default type for many conversions (such as Unmarshal), and if it is `string` we can also try to assert whether implements the `String` method.
Further more, is it reasonable to convert any other two types that is convertible (such as boolean `true` to int `1`)?
Please point out if there is anything I have not considered. Thanks in advance.
> feat: add int/int32/Stringer support when get atomicValue

- config/reader.go
we may need to reuse the reader.Value methods in some other place, such as in config resolver #1135
> refactor(config/reader): add readValue function

- config/config.go
- config/config_test.go
- config/options.go
- config/reader.go
- config/reader_test.go
using go template lib to replace placeholder to environment variable
like this:
```yaml
http:
server:
port: ${PORT:8080}
timeout: "${TIMEOUT}"
```
please help for code reviewing @ymh199478
thanks in advance :-)
> feat(config): support Resolver for config variable placeholders

- .github/workflows/go.yml
- .golangci.yml
- config/value.go
- encoding/form/form.go
- transport/grpc/client.go
- transport/http/context.go
使用 [golangci-lint](https://golangci-lint.run/) 来替代了 [golint](https://github.com/golang/lint) 检测，检测忽略了 `test` 文件，对于 `PR` 不主动检测旧的代码(非变更代码)，目前启用了以下[检测插件](https://golangci-lint.run/usage/linters)：
- revive
- staticcheck
- govet 
提交中包含了以下关联性改动：
- 对于新CI检测到的问题，本次PR**不对**问题进行修复，仅使用 `todo` 标记，标记问题。
- 提交对于 `冗余代码` 类型的问题，进行了更正。
- 根据 [golangci-lint-action/issues/23](https://github.com/golangci/golangci-lint-action/issues/23) 描述的内容，检测工具任务将会放在独立的 job 中进行。
- 添加了一个手动触发器用于手动触发 github action 任务
---
Merge 时请合并提交历史，closed #1173
> ci(github action): use golangci-lint to replace the deprecated golint

- config/value.go
`strconv.ParseFloat` 方法无需填写 `base` 参数，需要直接填写 `bitSize` 参数
> fix(config): strconv.ParseFloat use correct bitSize

- config/config_test.go
- config/env/env.go
- config/env/env_test.go
- config/env/watcher.go
- config/options.go
- config/reader.go
- config/value.go
resolve #1065, add new config source for reading environment variable
* Use `prefix` to filter the required variables
* Watching environment variables change are not support because I did not find a reasonable solution (any suggestions are welcome :). Using `Watch` will block until `Stop` is called.
* When the env var loaded into the `KeyValue` struct, the `Format` field is nil, so when we decode it, we need to change it to `string` or we will get a base64 code when using `json.Unmarshal` to clone a map
CC @ymh199478
> feat(env): add config env source

- config/config.go
- config/env/env_test.go
- config/options.go
- config/reader.go
When you want to use env vars to replace the placeholders in config file, you must put env source first to init the config. It's not very friendly to users.
Changed the error message to lowercase to comply with Go's error standard.
> fix(config): load env and file source order bug

- config/options.go
- config/options_test.go
- config/reader.go
支持将类似aaa.bbb的key展开成map[aaa]map[bbb]interface{}
这样可以实现通过key来覆盖文件中的结构体value，比如：
spring:
cloud:
consul:
discovery:
catalogServicesWatch:
enabled: false
会被spring.cloud.consul.discovery.catalogServicesWatch.enabled=true 覆盖
> support expand config keys

- config/env/env.go
- config/env/env_test.go
- go.mod
提取 `load(envStrings []string)` 方法以便单元测试
Merge 时请合并提交历史
> chore(config/env): minor refactor

- config/env/env.go
因为 . 在env里是非法字符，一般会用_来代替.的，所以需要替换回来
这样可以正确获取到 aa.bbb.ccc的value了
> replace env underscore to dot

- transport/http/resolver.go
之前的http resovler 一旦watch 返回error会导致整个流程return,现在改成先阻塞获取，再异步监听（永不退出）
> fix http resovler bug

- transport/grpc/resolver/discovery/builder.go
当时Watch 超时时，应该报错返回 不应该继续执行因为discoveryResolver的registry.Watcher 为空 会引起panic
> fix(grpc/resovler): create watcher overtime

- config/env/env_test.go
- config/file/file_test.go
When using os.TempDir() test may FAIL sometime, using t.TempDir() instead.
fixes #1288
> fix: using t.TempDir instead

- examples/blog/Makefile
在 kratos/examples/blog 执行 make errors 时报错 
./third_party: warning: directory does not exist.
> fix(example/blog/makefile): directory does not exist

- cmd/protoc-gen-go-http/http.go
For interfaces that require body, such as POST、PUT、PATCH, if no body is declared, the warning log is printed
> feat(cmd/pgh): add processing when generating HTTP code

- config/value.go
> fix(config): clean code

- config/file/file_test.go
- config/reader.go
There are some data races in current codes. These data races will break the Github Actions CI testing sometimes. The unit test in this PR could reproduce this issue. This data race will happen when Scan() and Load() in the same time.
This PR adds a lock to the config values map in order to avoid concurrent reads and writes.
data race message:
```
WARNING: DATA RACE
Read at 0x00c0004ac0b8 by goroutine 16:
github.com/go-kratos/kratos/v2/config.(*reader).Source()
/Users/windfarer/github/kratos/config/reader.go:58 +0x44
github.com/go-kratos/kratos/v2/config.(*config).Scan()
/Users/windfarer/github/kratos/config/config.go:131 +0x5b
github.com/go-kratos/kratos/v2/config/file.TestMergeDataRace.func1()
/Users/windfarer/github/kratos/config/file/file_test.go:308 +0x8d
Previous write at …
```
> fix(config): fix data race

- config/config.go
add watchers to config when load.
fixes #1318
> append config watchers when watch source

- metadata/metadata_test.go
> add: metadata test

- config/config.go
- config/env/watcher.go
- config/file/watcher.go
fixes #
code : [https://github.com/go-kratos/kratos/blob/55cf83062fc0f7b870fc0e6d277255eef2e305d9/config/config.go#L111](https://github.com/go-kratos/kratos/blob/55cf83062fc0f7b870fc0e6d277255eef2e305d9/config/config.go#L111)
> fix:config groutine(watch) leak

- config/config_test.go
- config/options.go
This PR fixes a bug where the default variable of a config option was trimmed when a colon was found
fixes #
> fix(config): Support colon as default value in config.yaml

- cmd/kratos/internal/run/run.go
修复 当使用 monorepo 目录结构时，使用 kratos run 命令，选择非最后一个服务启动时，执行目录错误。
- app
- - message
- - - cmd
- - user
- - - cmd
选择 message 启动时，目录会变成 /app/user/cmd/message。
> fix(cmd/run): command execution directory error

- middleware/tracing/metadata.go
当ctx不是kratos的context，则app.Name()会导致panic
> fix: if not kratos context then panic will result

- config/env/watcher.go
- config/env/watcher_test.go
> chore(config/env): polish watcher

- encoding/json/json.go
优化如下：
1、支持使用easyjson或定制实现方法，来提升序列化特别是反序列化的性能
2、api接口提交的body为空json体时，不需要进行反序列化，可以大幅提升性能
3、原先的反序列化方法中先进行反射，调整顺序到后面，避免每次都应用反射
> refactor(encoding): optimize json encoding

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/question.md
为 issues 加入了可爱的 icon 图标，并且对于文档类问题引导用户进入 kratos 文档网站，效果如下：
> chore: add icon in issues template

- contrib/registry/etcd/registry.go
- contrib/registry/etcd/registry_test.go
- contrib/registry/etcd/watcher.go
- hack/.lintcheck_failures
part of #1430
PTAL @tonybase. I add `error` return value to func `newWatcher`. Should I define a new error  instead of sentinel error?
> fix: Fix lint of files in contrib/registry/etcd

- errors/errors.go
- errors/errors_test.go
add converting support for grpc status whose details not contain any  `errdetails.ErrorInfo`
enhance errors.FromError
add converting support for grpc status whose details not contain any  `errdetails.ErrorInfo`
ie. a grpc status with code `codes.InvalidArgument` should be converted to `http.StatusBadRequest` instead of `UnknownCode`.
> fix: enhance errors.FromError

- transport/http/server.go
- transport/http/server_test.go
> fix:http server start panic when use Endpoint

- contrib/registry/discovery/discovery_helper.go
- contrib/registry/discovery/impl_discover.go
…a while translating ServiceInstance.
- discovery'watcher will not quit while `Watch` context canceled
- Metadata  lost while translate `ServiceInstance`
fix above issues
fixes #
> fix(registry/discovery): watch quit while context cancel; supplement metadata

- contrib/config/apollo/apollo.go
> feat: add backupConfigPath method

- transport/http/client.go
fixes # https://github.com/go-kratos/kratos/issues/1562
> feat(http): http client support service discovery in Do

- config/config.go
- config/config_test.go
- contrib/config/consul/config.go
- contrib/config/consul/config_test.go
- contrib/config/consul/go.mod
- contrib/config/etcd/config.go
- contrib/config/etcd/config_test.go
- contrib/config/etcd/go.mod
- contrib/config/kubernetes/config.go
- contrib/config/nacos/config.go
- examples/config/t/a.yaml
- examples/config/t/b.yaml
> feat(contrib/config): use key file extension as format & config load log

- cmd/protoc-gen-go-errors/errors.go
fix[cmd]: if enum is a word in proto file, it should be camel too.
For example: 
UNKNOWN field defined in errors proto file. 
`protoc-gen-go-errors` generate func IsUNKNOWN AND ErrorUNKNOWN, I think IsUnknown and ErrorUnknown will be better.
> fix(cmd): fixed a single word enum error

- cmd/kratos/internal/project/project.go
> fix(cmd/new): print the correct error message

- api/metadata/server.go
- cmd/kratos/internal/base/mod.go
- cmd/kratos/internal/base/path.go
- cmd/kratos/internal/change/get.go
- cmd/kratos/internal/proto/add/add.go
- cmd/kratos/internal/proto/add/proto.go
- cmd/kratos/internal/proto/client/client.go
- cmd/kratos/internal/proto/server/server.go
- cmd/kratos/internal/run/run.go
- config/env/env_test.go
- config/file/file.go
- config/file/file_test.go
- contrib/log/fluent/fluent_test.go
- contrib/registry/kubernetes/registry.go
- examples/tls/client/main.go
- examples/tls/tls_test.go
- log/filter_test.go
- log/helper_test.go
- transport/http/client.go
- transport/http/client_test.go
- transport/http/codec.go
- transport/http/codec_test.go
- transport/http/server_test.go
The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
> refactor: move from io/ioutil to io and os packages

- middleware/circuitbreaker/circuitbreaker.go
熔断器 client 返回的 middleware 中,  ctx 使用了 serverTransportKey 获取 value, 导致后续 panic
> fix: circuitbreaker use client context

- transport/http/client.go
The current http request ctx does not carry the user construct, so some timeouts and so on will fail.
fixes #
https://github.com/go-kratos/kratos/issues/1683
> transport/http: delay pass context.Context

- contrib/registry/nacos/watcher.go
> fix(nacos): call unsubscribe when watching is stopped

- cmd/protoc-gen-go-errors/template.go
修复： errors 插件生成的代码中， Isxxx 判断函数未对 入参 err 进行空判断。
> fix(cmd/proto-gen-http):  non nil assertion for error

- contrib/registry/nacos/registry.go
`cannot is empty` -> `can not be emptu`
> docs: some wrong err msg description

- cmd/protoc-gen-go-errors/errors.go
- cmd/protoc-gen-go-errors/errors_test.go
fix https://github.com/go-kratos/kratos/pull/1618
```
enum ErrorReason {
option (errors.default_code) = 500;
InvalidParameter = 0 [(errors.code) = 400];
}
```
Originally I got  IsInvalidParameter and ErrorInvalidParameter，but now i got IsInvalidparameter and ErrorInvalidparameter
This change compatible with  UPPER、Camel and Snake
> fix(cmd): fixed a camel word enum error (#1618)

- cmd/protoc-gen-go-http/http.go
fix grammar error:
is does not -> does not
> style: fix typo in cmd/protoc-gen-go-http/http.go(is does not -> does not)

- encoding/form/form.go
- encoding/form/proto_decode.go
- encoding/form/proto_encode.go
- transport/http/binding/encode.go
// The JSON representation for a FieldMask is a JSON string where paths are
// separated by a comma. Fields name in each path are converted to/from
// lower-camel naming conventions. Encoding should fail if the path name would
// end up differently after a round-trip.
references: https://github.com/protocolbuffers/protobuf-go/blob/master/encoding/protojson/well_known_types.go#L842
> fix(encoding/form): FieldMask are converted to/from lower-camel naming conventions.

- transport/grpc/client.go
I think `timeout` in `clientOptions` means the timeout of a grpc client calling, not discovery timeout, it's quite different.
In my project, I set the timeout to 0 with the purpose of no timeout, let the server decide how long to timeout, or use `context.WithTimeout` in the client request.
It works because kratos support that:
https://github.com/go-kratos/kratos/blob/e95452276f1f16490c358ae56afed459a8c6ef14/transport/grpc/client.go#L171-L175
However, it is broken down after v2.1.3, because the value has been used as discovery timeout, unfortunately, zero timeout do not work:
https://github.com/go-kratos/kratos/blob/e95452276f1f16490c358ae56afed459a8c6ef14/transport/grpc/resolver/discovery/builder.go#L68-L76
I noticed that the [commit](https://github.com/go-kratos/kratos/commit/5aeb14d381c2 …
> fix: remove the use of client timeout as discovery timeout

- contrib/registry/consul/client.go
- contrib/registry/consul/registry.go
> fix(registry/consul): fix can not find service in 20s

- contrib/registry/consul/registry.go
> fix(registry/consul):fix can't get service instance in async mode

- middleware/auth/jwt/jwt.go
- middleware/auth/jwt/jwt_test.go
Allow user put a customer header of JWT token while using the client auth middleware
> feat(middleware/auth/jwt): add customer header

- cmd/kratos/internal/base/install.go
- cmd/kratos/internal/upgrade/upgrade.go
google/gnostic: [refactor: rename apps to cmd and add go.mod](https://github.com/google/gnostic/commit/94bcf11351a51ca2ef62918cf8a7c7a5d2aa9b43)
fix: change installation package path for [protoc-gen-openapi](https://github.com/google/gnostic/tree/master/cmd/protoc-gen-openapi)
> fix: change installation package path for protoc-gen-openapi

- app.go
- config/config.go
- config/config_test.go
- contrib/config/apollo/apollo.go
- contrib/config/apollo/watcher.go
- log/global.go
- log/global_test.go
- middleware/recovery/recovery.go
- middleware/recovery/recovery_test.go
- transport/grpc/resolver/discovery/builder.go
- transport/grpc/resolver/discovery/resolver_test.go
- transport/grpc/server.go
- transport/http/resolver.go
- transport/http/server.go
Add global logger appliance, make logging in independence function easily.
fixes #
> feat(log): add global logger appliance, as process level default logger

- log/global.go
- log/global_test.go
Make global logger appliance as inner logger proxy, ensure logger change will effect to all sub-loggers.
fixes #
> make logger appliance as logger proxy

- transport/grpc/interceptor.go
- transport/grpc/server.go
- transport/grpc/server_test.go
> feat:add stream interceptor use ctx encapsulation

- errors/types.go
fix for unexpected placeholders due to escaping
sample: 
```go
msg := `values=%7B%22g`
err := errors.BadRequest("x-reason", msg)
fmt.Println(err.Message == msg) // false
fmt.Println(err.Message)        // values=%!B(MISSING)%!g(MISSING)
```
> fix: perhaps MISSING

- contrib/registry/consul/client.go
- contrib/registry/consul/registry.go
fix: consul heartbeat ttl not registered
> fix: consul heartbeat ttl not registered

- cmd/kratos/internal/proto/client/client.go
- cmd/kratos/internal/upgrade/upgrade.go
- transport/grpc/client_test.go
- transport/grpc/server_test.go
> fix: fix the latest version of lint problem

- config/config.go
fixes #1835 
If the type of new value not match the old one, value stay the old one.
> fix(config/config):fix type not match bug

- .github/workflows/go.yml
> build: add matrix strategy with go version

- examples/swagger/server/main.go
* remove redundant import reply
* not receive unused parameter ctx in SayHello function
* fix local variable log conflict with imported package
fixes #
> chore(examples): optimize typos of swagger/server

- cmd/kratos/internal/proto/server/server.go
- errors/errors_test.go
- examples/benchmark/test.sh
- examples/i18n/README.md
- examples/i18n/third_party/validate/validate.proto
- middleware/selector/selector.go
- third_party/validate/validate.proto
- transport/grpc/server_test.go
- transport/http/resolver.go
- transport/http/resolver_test.go
* matchs to matches
* contraint to constraint
* resovle to resolver
* ser to set
fix spelling mistake
> style(cmd/errors/examples/middleware/transport): fix common words' spelling mistakes

- cmd/kratos/internal/base/repo.go
- cmd/kratos/internal/base/repo_test.go
> fix: kratos command error on windows

- contrib/registry/consul/client.go
> feat: supprt non-kratos instance in consul registry

- app.go
> fix: starter parent ctx

- config/config.go
- contrib/registry/discovery/discovery.go
- contrib/registry/discovery/impl_discover.go
- contrib/registry/polaris/registry.go
- log/log.go
Normally we don't need to know the config load key info, only we need to be aware of it when debugging.
So change Info level to Debug
fixes #
> feat(log): log load config only when Debug level

- transport/http/server.go
> fix(transport): fix the problem that the request is not delivered correctly

- cmd/protoc-gen-go-errors/errors.go
- cmd/protoc-gen-go-errors/go.mod
- cmd/protoc-gen-go-errors/go.sum
> fix(cmd): fix lint problem

- cmd/protoc-gen-go-errors/errors.go
- cmd/protoc-gen-go-errors/go.mod
- cmd/protoc-gen-go-errors/go.sum
- contrib/registry/consul/client.go
- contrib/registry/consul/registry.go
Add `DeregisterCriticalServiceAfter` option
fixes #1904
> feat(registry): consul client add DeregisterCriticalServiceAfter option

- cmd/protoc-gen-go-errors/errors.go
Fix on a submit error caused by https://github.com/go-kratos/kratos/commit/4f21094a562287eec80df46e336cd65b8f745053
None of the commit unit test (Test_case2Camel) will pass
> fix(cmd):  generate error func name and unit test fail

- metadata/metadata.go
The function name in log should be AppendToClientContext
> fix(metadata): correct the function name in metadata log text

- transport/grpc/resolver/discovery/builder.go
- transport/grpc/resolver/discovery/resolver.go
> feat(discovery): provide an option to disable discovery debug log

- transport/http/binding/bind_test.go
fix bind test errors
fixes #1949
> fix bind test errors

- cmd/kratos/internal/run/run.go
> fix: fix kratos run when cmd number is one

- transport/http/codec.go
- transport/http/codec_test.go
It should not write any data when we don't need to return data to the client
fixes #1946
> fix(transport/http): responseEncoder should not write any data when it need to write nil

- contrib/registry/zookeeper/register.go
- contrib/registry/zookeeper/register_test.go
The current registrar with zookeeper doesn't have any method for auth.
I think add a simple digest acl support is necessary.
> feat(registry): contrib/registry/zookeeper add digest acl support

- log/helper_writer.go
- log/helper_writer_test.go
- options_test.go
Implemented io.Writer, easy to use in standard library, like log.New.
`Helper` can set to `http.Server{}.ErrorLog`.
Example 1(transport/http):
```go
// import stdlog "log"
// import log "github.com/go-kratos/kratos/v2/log"
// file: https://github.com/go-kratos/kratos/blob/main/transport/http/server.go#L153
srv.Server = &http.Server{
Handler:   FilterChain(srv.filters...)(srv.router),
// record http error log to helper.
ErrorLog:  stdlog.New(srv.log.WithWriterLevel(log.LevelError), "", 0),
}
```
Example 2 (go-redis):
```go
// import stdlog "log"
// import log "github.com/go-kratos/kratos/v2/log"
helper := log.NewHelper(logger, log.WithWriterLevel(log.LevelInfo))
redis.SetLogger(stdlog.New(helper, "", 0))
```
> feat(log): Helper implemented io.Writer

- README_zh.md
docs: correct the typo of "Swaager UI" to "Swagger UI" in `README_zh.md`.
> docs: fix a typo in README_zh.md

- README.md
Signed-off-by: vgjm <vgjm456@qq.com>
When I follow the Quick Start tutorial in the README.md, a promblem occured:
```
root@c093b0581829:/workspace# kratos run
go: updates to go.mod needed; to update it:
go mod tidy
ERROR: exit status 1
```
> fix: add 'go mod tidy' cmd to make quick-start available

- contrib/config/consul/config.go
- contrib/config/etcd/config.go
delete redundant type conversion
> fix: delete redundant type conversion

- cmd/protoc-gen-go-http/http.go
Generator cannot parse multiple message fields and i fixed it ;)
I have RPC method:
```
rpc UpsertLevel (UpsertLevelRequest) returns (UpsertLevelResponse) {
option (google.api.http) = {
post: "/v1/organization/{level.organization_id}/levels"
body: "level"
response_body: "level"
additional_bindings: {
put: "/v1/organizations/{level.organization_id}/levels/{level.id}"
body: "level"
response_body: "level"
}
};
}
```
and message:
```proto
message UpsertLevelRequest {
message Level {
string id = 1;
string organization_id = 2;
// ... and other fields
}
Level level = 1;
}
```
An error occurs during generation: `ERROR: The corresponding field 'level.id' declaration in message could not be found in …
> fix(protoc-gen-go-http): buildMethodDesc for two and more message field

- cmd/protoc-gen-go-http/http.go
- cmd/protoc-gen-go-http/template.go
fix:#1987
Keep the original content when http is generated
> fix:#1987 Http and grpc generate route alignment

- cmd/protoc-gen-go-errors/template.go
protoc-gen-go-errors generated function comments have extra blank lines.
like this:
```go
// 未知的错误
func ErrorUnknownError(format string, args ...interface{}) *errors.Error {
return errors.New(500, ErrorReason_UNKNOWN_ERROR.String(), fmt.Sprintf(format, args...))
}
```
> fix: protoc-gen-go-errors generated function comments have extra blank lines.

- pkg/net/http/blademaster/routergroup.go
- pkg/net/http/blademaster/server.go
For the Kratos V2 server:
```go
srv := http.NewServer()
pb.RegisterGreeterHTTPServer(srv, &server{})
engine := bm.Default()
engine.PrefixFunc("/helloworld", func(ctx *bm.Context) {
srv.ServeHTTP(ctx.Writer, ctx.Request)
})
```
> http/bm: add prefix matcher for the path prefix

- transport/http/codec.go
- transport/http/server.go
auto configure:
```go
func init() {
exporter, err := metric.NewExporter()
if err != nil {
panic(err)
}
http.HandleFunc("/metrics", exporter.ServeHTTP)
global.SetMeterProvider(exporter.MeterProvider())
}
```
> http: handle default mux

- contrib/opensergo/README.md
- contrib/opensergo/go.mod
- contrib/opensergo/opensergo.go
add some fields for opensergo reportMeatadata
I'm still not sure about some parts, any advice is welcome.
* ~~Is there any way to get the HTTP options information defined in proto file~~
* For the `description` field, I'm not sure if it should be read from proto file automatically or use a config option for users.
* For the `node` field, do we need to assume the deployment environment, such as kubernetes, to get some information automatically.
> feat(contrib/opensergo): add opensergo reportMetadata fields

- app.go
- app_test.go
- options.go
- options_test.go
```go
logger, err := logimpl.NewLogger()
if err != nil {
log.Fatal(err)
}
defer logger.Close()
app := kratos.New(
kratos.Name(Name),
kratos.Logger(logger), // log.SetLogger(logger)
kratos.Version(Version),
kratos.Server(httpSrv, grpcSrv),
)
if err := app.Run(); err != nil {
log.Fatal(err)
}
```
> app: fix instance nil when not registered

- cmd/kratos/internal/proto/server/server.go
- cmd/kratos/internal/proto/server/server_test.go
- add ucFirst function and unit test at cmd/kratos/internal/proto/server/server.go
- fix the [method name style bug ](https://github.com/go-kratos/kratos/issues/2089)
> fix: kratos proto server cmd method name bugfix (#2089)

- app.go
**问题**：服务在收到 `os.Signal` 后退出，但并未返回服务在关闭过程中出现的错误。
**原因**：在 `errgroup` 中返回了 `ctx.Err()`。按照原有的代码逻辑，如果不考虑极端情况，在收到 `os.Signal` 后 `errgroup` 都会返回 `context.Canceled`，因为 `errgroup` 只会返回第一个错误，而 `context.Canceled` 这个错误在 `Run` 方法中会被忽略，这就导致了 `Run`  未捕获到服务关闭过程中的错误。
**p.s.** 这里把 `for` 代码也删了，因为考虑到 `ctx.Err()` 仅会返回 `context.Canceled` 以及 `context.DeadlineExceeded`，结合上下文，该 `ctx` 不会出现超时的情况，所以不需要返回 `ctx.Err()`。
> fix: catch server stop error

- contrib/opensergo/opensergo_test.go
coverage: 88.0% of statements
part of https://github.com/go-kratos/kratos/issues/2135
> test(contrib): add unit test for opensergo.go

- cmd/kratos/internal/proto/proto.go
we input `kratos proto` in command line without any tips
> fix: remove the output of the proto command

- cmd/kratos/internal/base/repo.go
展示详细错误信息给用户,例如:
from:
ERROR: Failed to create project(exit status 128)
to:
exit status 128
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
> fix: show git output

- contrib/registry/etcd/watcher.go
read value from etcd twice if no such opOption
> feat(contrib):add etcd watcher withKeysOnly option

- encoding/form/well_known_types_test.go
add tests for `encoding/form/well_konw_types.go `
part of #2147
> test(encoding/form): well konw types test (#2147)

- middleware/circuitbreaker/circuitbreaker_test.go
- middleware/logging/logging_test.go
- middleware/metadata/metadata_test.go
- middleware/metrics/metrics_test.go
- middleware/ratelimit/ratelimit_test.go
- middleware/recovery/recovery_test.go
- middleware/selector/selector_test.go
- middleware/tracing/metadata_test.go
- middleware/tracing/span_test.go
- middleware/tracing/statsHandler.go
- middleware/tracing/statsHandler_test.go
- middleware/tracing/tracer_test.go
- middleware/tracing/tracing_test.go
```
github.com/go-kratos/kratos/v2/middleware/auth/jwt/jwt.go:56:                   WithSigningMethod       100.0%
github.com/go-kratos/kratos/v2/middleware/auth/jwt/jwt.go:65:                   WithClaims              100.0%
github.com/go-kratos/kratos/v2/middleware/auth/jwt/jwt.go:72:                   WithTokenHeader         100.0%
github.com/go-kratos/kratos/v2/middleware/auth/jwt/jwt.go:79:                   Server                  87.5%
github.com/go-kratos/kratos/v2/middleware/auth/jwt/jwt.go:134:                  Client                  91.3%
github.com/go-kratos/kratos/v2/middleware/auth/jwt/jwt.go:172:                  NewContext              100.0%
github.com/go-kratos/kratos/v2/middleware/auth/jwt/jwt.go:177:                  FromContext             100.0% …
```
> tests(coverage): Increase middleware tests coverage

- options_test.go
Part of https://github.com/go-kratos/kratos/issues/2147
> test(options): increase tests coverage

- log/global_test.go
- log/log_test.go
log tests coverage: 81.6% -> 90.8%
part of https://github.com/go-kratos/kratos/issues/2147
> test(log): increase tests coverage

- contrib/config/polaris/config.go
- contrib/config/polaris/config_test.go
Injected polaris config client api is not used properly.
Use injected client properly.
> fix(contrib/config/polaris): Use injected client properly

- cmd/kratos/internal/run/run.go
> feat: support passing program args with run cmd

- internal/host/host.go
- fix bug #2297 
- rename: `lowest` -> `minIndex`
- ~~use const `math.MaxInt` replace `int(^uint(0) >> 1)`~~
https://go.dev/doc/go1.17
https://github.com/go-kratos/kratos/issues/2297
> fix(internal/host): Extract can't return the minium index ip

- Makefile
- api/metadata/server.go
- errors/errors.go
part of #2108 
上个提交应该没有考虑后续 `go generate` 会产生覆盖的情况，此提交补充。
> fix: add "make proto" for generating pb.go

- transport/grpc/codec_test.go
supplement the unit testing of transport/grpc, increase coverage to 92.7% from 89.8%.
part of https://github.com/go-kratos/kratos/issues/2354
> test: supplement the unit testing of transport/grpc

- contrib/opensergo/opensergo_test.go
```
err := os.WriteFile("test.json", []byte(fileContent), 0o644)
if err != nil {
t.Fatalf("ioutil.WriteFile error:%s", err)
}
```
code has changed but log hasn't.
> fix: typo for log

- transport/grpc/resolver/discovery/builder_test.go
replace grpc resolver.Target deprecated field
> cleanup: replace grpc resolver.Target deprecated field

- cmd/kratos/version.go
- cmd/protoc-gen-go-errors/version.go
- cmd/protoc-gen-go-http/version.go
- contrib/encoding/msgpack/go.mod
- contrib/log/aliyun/go.mod
- contrib/log/fluent/go.mod
- contrib/log/logrus/go.mod
- contrib/log/tencent/go.mod
- contrib/log/zap/go.mod
- contrib/metrics/datadog/go.mod
- contrib/metrics/prometheus/go.mod
- contrib/opensergo/go.mod
- contrib/registry/consul/go.mod
- contrib/registry/discovery/go.mod
- contrib/registry/etcd/go.mod
- contrib/registry/kubernetes/go.mod
- contrib/registry/nacos/go.mod
- contrib/registry/polaris/go.mod
- contrib/registry/zookeeper/go.mod
- transport/http/codec.go
- version.go
> deps: upgrade kratos version v2.5.1

- transport/http/server.go
Add feature:option of mux router prefix path.
在开发过程中，我们有给当前http服务加统一前缀的需求。
调整了 http.NewServer 函数，增加 PathPrefix option。通过mux的PathPrefix函数和SubRouter创建带有前缀的Router，并覆盖原Router。
> [Feature] add path prefix for http server

- contrib/log/fluent/fluent_test.go
- contrib/registry/eureka/client.go
Resource leakage may occur. Call 'defer' in the 'for' loop.
case: https://go.dev/doc/effective_go#defer
> fix: call `defer` in `for` loop

- api/metadata/server.go
It's out of order on the reply of ListServices, which is so complex for human reading.
> fix(metadata): sort services by lexicographical order on ListServices

- cmd/kratos/internal/change/get.go
- cmd/protoc-gen-go-http/http.go
- contrib/opensergo/opensergo.go
- contrib/opensergo/opensergo_test.go
- contrib/registry/eureka/client.go
- transport/http/binding/bind_test.go
- transport/http/client_test.go
- transport/http/context_test.go
- transport/http/redirect_test.go
- transport/http/router_test.go
- transport/http/server_test.go
> cleanup: using constants instead of literals

- contrib/log/aliyun/aliyun.go
- contrib/log/aliyun/aliyun_test.go
- contrib/log/tencent/tencent.go
- contrib/log/tencent/tencent_test.go
- log/level.go
- log/level_test.go
- float32 
Convert string precision loss
```diff
switch v := v.(type) {
case float32:
-  key = strconv.FormatFloat(float64(v), 'f', -1, 64) 
+  key = strconv.FormatFloat(float64(v), 'f', -1, 32) 
```
- uint 
Convert uint with `Itoa`, will be treated as a signed int conversion,`MaxUint` will be converted to - 1, the correct return should be 18446744073709551615
> fix(log): toString float32 precision loss and convert uint use `FormatUint`

- config/config.go
- config/config_test.go
- config/env/env.go
- config/env/watcher.go
- config/file/file_test.go
- config/file/format_test.go
- config/file/watcher.go
- config/options_test.go
- config/reader.go
- config/reader_test.go
- config/value.go
- config/value_test.go
- contrib/metrics/datadog/go.mod
- code style tweaks
- abstracts some methods
> style(config): code style tweaks and abstracts some methods

- log/filter.go
- log/filter_test.go
This PR fixes a bug where a `filterFunc` couldn't filter/override a keyval. This was a regression introduced [here](https://github.com/go-kratos/kratos/pull/1901/files).
The root cause was that to take into account the log prefix, we made a copy of the original keyvals and the filter was applied on such copy. This means that any filterFunc that was meant to override the original keyvals, was changing the copy instead.
This PR changes the code to apply a filter func in both the prefix and the log keyvals. The test cases have been also updated to cover all the scenarios.
Refs #1897
> fix(filter): filter out keyvals if keyFunc is provided

- app.go
- app_test.go
- options.go
- options_test.go
add app Before and Afters option
> feat: add app Before and Afters option

- selector/global.go
fix https://github.com/go-kratos/kratos/issues/2488
> fix(selector): set global do not work

- middleware/circuitbreaker/circuitbreaker.go
add WithCircuitBreaker for custom breaker
```go 
// WithCircuitBreaker with circuit breaker genFunc.
func WithCircuitBreaker(genBreakerFunc func() circuitbreaker.CircuitBreaker) Option {
return func(o *options) {
o.group = group.NewGroup(func() interface{} {
return genBreakerFunc()
})
}
}
```
fixes #2534
> feat(circuitbreaker): add WithCircuitBreaker to fix WithGroup is useless

- middleware/logging/logging.go
- middleware/logging/logging_test.go
The **logging middleware** is logging sensitive data from requests, one strategy to fix it is by implementing the `fmt.Stringer` interface, but when we use the gRPC generators the `String` method is already implemented and there is no other alternative to filter sensitive data from the request object.
this PR adds a `Redacter` interface wich in case of being implemented for the request object will have more priority than the `fmt.Stringer`, giving the option to provide a string version of the request only for loging without affecting the auto-generated code.
> feat(middleware): redacter interface for logging

- contrib/registry/zookeeper/watcher.go
解决以下问题：
* 使用zookeeper做服务发现时，如果目标服务的节点未创建，导致watcher停止的问题。
* 当服务A依赖服务B，在第一次运行时，如果服务A先于B之前启动
* 以下截图部分代码会导致服务A当前的watcher停止（ErrWatcherStopped），服务A必须重启之后才能获得服务B的实例。
> fix(registry): add zookeeper exists watcher when the node does not exist

- transport/grpc/server.go
support grpcdebug
https://github.com/grpc-ecosystem/grpcdebug
> feat: grpc use the admin api

- transport/http/codec.go
- transport/http/codec_test.go
> feat(transport/http): request body read multiple times

- cmd/kratos/go.mod
- cmd/kratos/go.sum
There are 1 security vulnerabilities found in gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
- [CVE-2022-28948](https://www.oscs1024.com/hd/CVE-2022-28948)
Upgrade gopkg.in/yaml.v3 from v3.0.0-20210107192922-496545a6307b to 3.0.0 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
> fix(sec): upgrade gopkg.in/yaml.v3 to 3.0.0

- cmd/protoc-gen-go-http/http.go
- cmd/protoc-gen-go-http/template.go
add comment to http server interface, we can find the method use. 
easy to find what is the http server method use.
nothing
> feat(cmd/protoc-gen-go-http): add comment to http server interface method

- middleware/recovery/recovery.go
- middleware/recovery/recovery_test.go
Add latency to the recover handler context
fixes #2597
> feat: Add latency to the recover handler context

- transport/grpc/client.go
When service name is not passed, gRPC health server will set a service with null key
```
// NewServer returns a new Server.
func NewServer() *Server {
return &Server{
statusMap: map[string]healthpb.HealthCheckResponse_ServingStatus{"": healthpb.HealthCheckResponse_SERVING},
updates:   make(map[string]map[healthgrpc.Health_WatchServer]chan healthpb.HealthCheckResponse_ServingStatus),
}
}
```
At the same time, if the error returned by the peer service is that the healthcheck is not implemented, the connection status is also available. gRPC believes that the connection is available as long as the health check is passed or the error returned is not implemented
```
for {
err = s.RecvMsg(resp)
// Reports healthy for the LBing purposes if health check is not implemented in the server.
if …
```
> feat: support grpc balancer health check

- transport/grpc/resolver/discovery/resolver.go
> fix(transport/grpc/resolver/discovery/resolver.go): remove attributes.Attributes.New()

- contrib/registry/servicecomb/registry.go
> fix(contrib/registry/servicecomb): ticker was shutdown prematurely

- contrib/registry/servicecomb/watcher.go
- selector/p2c/p2c.go
- selector/wrr/wrr.go
> chore: make lint happy

- .golangci.yml
- contrib/opensergo/opensergo.go
- transport/grpc/client.go
- transport/grpc/resolver/discovery/builder.go
- transport/grpc/resolver/discovery/resolver.go
- transport/grpc/server.go
- transport/http/binding/bind.go
- transport/http/binding/bind_test.go
- transport/http/binding/encode.go
- transport/http/client_test.go
- transport/http/codec.go
- transport/http/resolver.go
- transport/http/server.go
> refactor(transport): format import and init slice cap

- middleware/tracing/statshandler.go
- middleware/tracing/statshandler_test.go
> fix(middleware/tracing): rename hump filename

- metadata/metadata.go
- metadata/metadata_test.go
- middleware/auth/jwt/jwt_test.go
- middleware/metadata/metadata.go
- middleware/metadata/metadata_test.go
- middleware/selector/selector_test.go
- middleware/tracing/tracing_test.go
- transport/grpc/transport.go
- transport/http/transport.go
- transport/transport.go
Adding Add/Values func for transport and metadata layers, fixed tests a… #2771
> refactor: metadata supports key corresponding to multiple values

- middleware/tracing/tracer.go
- middleware/tracing/tracing.go
Tracing middleware uses global provider by default, but allow custom providers.
fixes #2802
No break changes.
> fix(tracing): use global provider by default, but allow custom providers

- cmd/protoc-gen-go-errors/errorsTemplate.tpl
- cmd/protoc-gen-go-errors/template.go
- cmd/protoc-gen-go-http/httpTemplate.tpl
- cmd/protoc-gen-go-http/template.go
> chore: embedding template

- errors/errors_test.go
google.golang.org/grpc v1.55.0 已经移除了grpc_tesing模块，errors单元测试看起来也没有必要依赖这个包，因此移除依赖
> chore: remove the dependency of grpc_testing module

- cmd/kratos/internal/project/project.go
> fix: fix go import path when add project --nomod

- encoding/proto/proto.go
- encoding/proto/proto_test.go
> fix: http parse pb message body panic

- .github/workflows/go.yml
> update polaris-standalone docker image

- cmd/protoc-gen-go-http/http.go
- cmd/protoc-gen-go-http/main.go
```shell
flags:
-omitempty=false
-omitempty_prefix=/api
protoc --proto_path=.  --go-http_out=omitempty=false,omitempty_prefix=/api,paths=source_relative:. service.proto
rpc SayHello (HelloRequest) returns (HelloReply) {
option (google.api.http) = {
get: ""
}
}
generated path:
/api/helloworld.v1.Greeter/SayHello
```
> feat: add omitempty prefix to rule path

- log/filter.go
- log/filter_test.go
- log/log.go
- middleware/tracing/tracing_test.go
fix logging middle don't get trace_id value when logger is filterLogger
#2570 
#2571
> fix logging middle don't get trace_id value when logger is filterLogger

- encoding/form/form_test.go
- encoding/form/proto_decode.go
- encoding/form/proto_decode_test.go
The field is of type map and cannot be decode. (proto type `map<string,string>` cannot be decode)
修复 form 对 map 类型的错误解析，导致无法拿到 map 的数据
resolves #2495
> fix(encoding/form): failed to decode form map type

- transport/grpc/server.go
- transport/http/server.go
transport/server.go exposes an Endpoint() option that allows to specify the endpoint when defining the server, instead of manually specifying it for each server when creating a new app.
https://github.com/go-kratos/kratos/blob/32b1d13f904f021f9e5d275c3e19c9f008efbca0/transport/grpc/server.go#L119
fixes/resolves #2902
> feat(transport): add endpoint option for server

- cmd/protoc-gen-go-http/httpTemplate.tpl
Cannot bind Query and Body at the same time when you make a Post request;, should be able to bind them at the same time
fixes #2907
> feat: add bindQuery default

- encoding/form/proto_decode.go
- encoding/form/proto_decode_test.go
fix https://github.com/go-kratos/kratos/pull/2468
> bugfix: fix map decode

- hack/resolve-modules.sh
- hack/tools.sh
Fix a typo variable in the shell script. Like `KRATOS` NOT `KRAOTS`.
This PR is Pass to [CI Test](https://github.com/Mo3et/kratos/actions?query=event%3Apull_request) in my fork repo.
none.
none.
> chore: fix typo variable in shell script

- transport/grpc/client.go
- transport/grpc/client_test.go
Refer to https://github.com/go-kratos/kratos/pull/2736#issue-1625835510 grpc client healthCheck is force to enable.
But in https://github.com/grpc/grpc/blob/master/doc/health-checking.md#grpc-health-checking-protocol, the `Watch()` returns  a stream resp:
```proto
rpc Watch(HealthCheckRequest) returns (stream HealthCheckResponse);
```
In some special business usecase，I must use nginx or any other gateway to proxy the grpc request. But it is not support stream resp and it will always return write_timeout. It will take some error in my case like:
`rpc error: code = Unavailable desc = last connection error: connection active but received health check RPC error: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR"`
The nginx plus has impl the …
> feat(transport/grpc): grpc client supports health check option

- transport/http/router.go
- transport/http/router_test.go
This PR will fix data race issues caused by object reuse with sync.Pool.
more detail for bug issue: https://github.com/go-kratos/kratos/issues/3070
> remove context sync.Pool to avoid data races.

- app.go
Use new context when starting server so that requests are not canceled during graceful shutdown
fixes/resolves #3096
none
> fix: `sctx` cause request ctx canceled during graceful shutdown

- config/config.go
- config/config_test.go
- config/options.go
- config/options_test.go
- config/reader.go
- config/reader_test.go
> feat(config): config support custom merge config

- encoding/form/well_known_types.go
- encoding/form/well_known_types_test.go
Server local time should be used, not UTC(), there is time difference
> fix(encoding/form): time with the location set to local time

- contrib/registry/consul/client.go
this is will happen when heartbeat start after deregister, some error like below:
```
'[Consul] update ttl heartbeat to consul failed! err=Unexpected response code: 404 (Unknown check ID "xxxxxx". Ensure that the check ID is passed, not the check name.)
```
> fix: fix consul heartbeat 404 error

- transport/http/server.go
- transport/http/server_test.go
pprof will be registered to DefaultServeMux by default, and go-kratos's NotFoundHandler and MethodNotAllowedHandler will use DefaultServeMux, resulting in the inability to flexibly control the switch of pprof. 
This PR adds ServerOption to modify NotFoundHandler and MethodNotAllowedHandler
> feat: add server option for NotFoundHandler and MethodNotAllowedHandler

- app.go
clear the err after the app wait err handing, to avoid the err return when afterStop is not set.
> fix: clear err after app stop err handling

- encoding/form/form_test.go
- encoding/form/proto_encode_test.go
Fix test failed.
fixes/resolves #3181 
Forget to pull upstream before release a PR. Do It again.
> fix: test failed on other timezone.(#3181)

- contrib/log/zap/zap.go
- contrib/log/zap/zap_test.go
Use `zlog.Info(xxx)` will output multiple `msg` pairs:
```go
zlog.Info("hello wolrd")
output:		{"level":"info","msg":"","msg":"hello world"}
we need: 	{"level":"info","msg":"hello world"}
```
> fix: zap log print out multiple `msg`

- cmd/protoc-gen-go-http/httpTemplate.tpl
Consider these codes that generated by "protoc-gen-go-http":
```go
// "api/helloworld/v1/greeter_http.pb.go"
func (c *GreeterHTTPClientImpl) SayHello(ctx context.Context, in *HelloRequest, opts ...http.CallOption) (*HelloReply, error) {
var out HelloReply
pattern := "/helloworld/{name}"
path := binding.EncodeURL(pattern, in, true)
opts = append(opts, http.Operation(OperationGreeterSayHello))
opts = append(opts, http.PathTemplate(pattern))
err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
if err != nil {
return nil, err
}
return &out, err // <--
}
```
It's better to return `&out, nil` instead of `&out, err`.
> fix(protoc-gen-go-http): return nil if err == nil。

- transport/http/binding/encode_test.go
A small improve for test code.
> fix(transport/http): no need to call EncodeURL twice in test

- encoding/form/proto_encode.go
fix: use .MapKey to get key's FieldDescriptor
> fix: use .MapKey to get key's FieldDescriptor

- .github/workflows/go.yml
> build(go): Added support for go1.22.x

- .github/workflows/lint.yml
Upgrade `golangci/golangci-lint-action` from v3 to v4
> build(lint): upgrade `golangci/golangci-lint-action`

- log/helper.go
- log/helper_test.go
log 在在开发中会使用很多 Debug / Debugf 日志，在生产服务中可能会配置为 Info 级以上  
但 log.Helper 函数中会在进入
```go
h.logger.Log(LevelDebug, h.msgKey, h.sprintf...  )
``` 
提前运行了 `fmt.Sprint`、`fmt.Sprintf` 在较高并发的情况下，带来了非常高的字符串拼接耗损。
fixes/resolves #3209
> feat(log): Prevent log.Helper sprintf from running early #3209

- transport/http/binding/encode_test.go
> fix: remove duplicate test codes.

- contrib/registry/polaris/registry.go
北极星服务发现基本不可用,在项目初始化时如果依赖的服务节点没有变化(推送watch),那么Next()函数会阻塞,导致后启动的服务获取不到其他节点信息.
> fix: polaris registry bug: nodes is empty at startup

- middleware/logging/logging.go
- middleware/logging/logging_test.go
Fix caller path issue in logging middleware.
fixes/resolves #3133
Testing code maybe a little bit hard for understanding.
> fix: logging middleware caller issue #3133

- contrib/registry/etcd/registry.go
In the original code, the management of the "heartbeat" coroutine in the Registry relies on the "option.ctx" passed in from the outside. In the default case, this may lead to the "heartbeat" goroutine being unable to correctly determine whether it should end based on the state of the context during its execution.
In reality, in addition to using a timeout context for managing the Register and DeRegister methods, the Registry also needs a separate context to control its lifecycle.
This context should obviously be controlled by the Registry itself: initialized during Register and canceled during DeRegister.
This is the origin and purpose of this PR.
在原本的代码中, Registry的heartbeat协程的管理由外部传入的option.ctx管理, 在默认的情况下, 这有可能导致heartbeat goroutine在运行过程中无法正确的通过context 的状态来判断是否应该结束.
实际上, 除了在管理 Register 以及 …
> fix: etcd registry lifecycle

- contrib/registry/consul/registry.go
- contrib/registry/consul/registry_test.go
- contrib/registry/consul/service.go
- contrib/registry/consul/watcher.go
> fix(consul): unable to recreate after canceled the consul watch

- transport/http/context.go
- transport/http/context_test.go
Add an `Unwrap` method for returning underlying response writer.
resolves #3253
> feat(transport/http): add unwrap method for returning underlying response writer

- encoding/form/form_test.go
- encoding/form/proto_decode.go
- encoding/form/proto_encode_test.go
1. The mock time zone should not be UTC. The time zone should be fixed when passing parameters.
2. decode `parseMessage` should also use the current time zone time
fix issue: https://github.com/go-kratos/kratos/issues/3181
> fix(encoding/form): `Timestamp` use local time and fix test wrong mock time zone

- contrib/polaris/router.go
https://github.com/go-kratos/kratos/security/code-scanning/3
> fix(contrib/polaris): incorrect conversion between integer types

- contrib/opensergo/opensergo.go
- contrib/polaris/router.go
https://github.com/go-kratos/kratos/security/code-scanning/2
> fix(contrib/opensergo): incorrect conversion between integer types

- contrib/registry/nacos/watcher.go
This submission can solve the channel blocking problem during service discovery, as well as the channel message missing problem when the GRPC idle state changes. ﻿
The first scenario is when both the configuration center and registration center are initialized at the same time during service startup, and the SubscribeCallback method will be triggered twice, throwing the error "over time discovering the creation of observers", resulting in a discovery failure. The second scenario occurs after NotLoadCacheAtStart: true. When grpc exits the idle state, calling newWatcher again will not trigger the SubscribeCallback method, causing the Next function to be blocked and the service to be unable to communicate.
> fix(contrib/registry/nacos): Abnormal blocking of the Subscribe and Next methods.

- encoding/form/form.go
- encoding/form/form_test.go
Can modify the form default encode or decode default tag.
- Change encoder and decoder tag name to `form`:
```
go build "-ldflags=-X github.com/go-kratos/kratos/v2/encoding/form.tagName=form"
```
- In the same way, a variable overridable at link time is also provided to override the tag name used in the test suite:
```
go test "-ldflags=-X github.com/go-kratos/kratos/v2/encoding/form.tagNameTest=form"
```
> faat(encoding/form): allow change the default encoder and decoder tag name

- config/options.go
- config/options_test.go
Convert to type based on the followed pattern:
- bool: true/false
- float64: has(.) parseFloat
- int64: parseInt
- string: default
- ${key:"defaultValue"}
fix: https://github.com/go-kratos/kratos/issues/3198
> feat: parsing config input and convert to match the type

- transport/http/server.go
- transport/http/transport.go
```go
cookie := http.Cookie{
Name:     "exampleCookie",
Value:    "Hello world!",
Path:     "/",
MaxAge:   3600,
HttpOnly: true,
Secure:   true,
SameSite: http.SameSiteLaxMode,
}
// Use the http.SetCookie() function to send the cookie to the client.
http.SetCookie(ctx, cookie)
```
> adds Set-Cookie method to the HTTP transport.

- cmd/kratos/version.go
- cmd/protoc-gen-go-errors/version.go
- cmd/protoc-gen-go-http/version.go
- contrib/config/apollo/go.mod
- contrib/config/consul/go.mod
- contrib/config/etcd/go.mod
- contrib/config/kubernetes/go.mod
- contrib/config/nacos/go.mod
- contrib/config/polaris/go.mod
- contrib/encoding/msgpack/go.mod
- contrib/log/aliyun/go.mod
- contrib/log/fluent/go.mod
- contrib/log/logrus/go.mod
- contrib/log/tencent/go.mod
- contrib/log/zap/go.mod
- contrib/log/zerolog/go.mod
- contrib/opensergo/go.mod
- contrib/polaris/go.mod
- contrib/registry/consul/go.mod
- contrib/registry/discovery/go.mod
- contrib/registry/etcd/go.mod
- contrib/registry/eureka/go.mod
- contrib/registry/kubernetes/go.mod
- contrib/registry/nacos/go.mod
- contrib/registry/polaris/go.mod
- contrib/registry/zookeeper/go.mod
- version.go
- break(metrics): refactor kratos metrics with otel metrics (#3256)
- feat: parsing config input and convert to match the type (#3306)
- fix(contrib/registry/nacos): Abnormal blocking of the Subscribe and Next methods. (#3320)
- fix(contrib/opensergo): incorrect conversion between integer types (#3309)
- fix(contrib/polaris): incorrect conversion between integer types (#3300)
- fix: com patile both map[kratos] and map.kratos for a map type in the query parameters (#3284)
- chore(middleware/metrics): if requests and seconds are nil, return directly (#3298)
- chroe: chore update (#3367)
- build(deps): bump golang.org/x/net from 0.19.0 to 0.23.0 (#3295)
- build(deps): bump golang.org/x/net in /contrib/registry/servicecomb (#3285)
- build(deps): bump golang.org/x/net in /contrib/config/etcd …
> deps: upgrade kratos version to v2.8.0

- transport/grpc/resolver/discovery/resolver.go
fix grpc discovery no filter redundant endpoints in update instance
> fix: filter redundant endpoints invalid

- transport/grpc/resolver/discovery/builder.go
使用etcd 服务发现, 当etcd leader 意外终止时, grpc resolver 将无法获取目标服务endpoint, 导致服务调用失败.
暴露这个错误可以使用户获得一定的兜底能力, 且不影响框架的功能及完整性.
用户更为无感的处理上述bug, 需要进一步修复.
> feat(resolver/discovery): expose create watcher timeout error

- contrib/polaris/registry.go
- contrib/polaris/registry_test.go
fix concurrent map iteration and map write
#3361
> fix(registry/polaris): fix concurrent map iteration and map write #3361

- cmd/kratos/internal/change/get.go
leagy changelog is lose `Build` Group.
before effect:
After effect:
> feat: create build Group in changelog generate.

- .github/workflows/go.yml
- contrib/registry/consul/registry_test.go
The previous unit test did not recycle the watchresolved tick go routine. It is used to get the latest service information regularly. When running multiple unit tests, the v1/health/service/ interface of consul will be called concurrently, resulting in the X-Consul-Index returned by the server is not the expected result.
> fix: unit test Recycle watch resolver tick goroutine

- .github/pull_request_template.md
- .golangci.yml
- README.md
- ROADMAP.md
- cmd/kratos/internal/proto/server/server.go
- config/options_test.go
- contrib/config/apollo/README.md
- contrib/config/kubernetes/README.md
- contrib/log/aliyun/aliyun.go
- contrib/registry/kubernetes/registry_test.go
- encoding/form/form_test.go
- encoding/form/proto_decode.go
- internal/matcher/middleware.go
- log/README.md
- log/filter_test.go
- middleware/tracing/metadata.go
- third_party/validate/validate.proto
- transport/grpc/resolver/discovery/builder.go
- transport/grpc/resolver/discovery/resolver.go
- transport/http/resolver.go
Just thought I'd contribute some typo fixes that I stumbled on in the samples area. Nothing controversial (hopefully).
FYI, the typos are:
* selecter (6)
* matchs (5)
* separater (3)
* actural (2)
* specifes (2)
* alway (1)
* uarry (1)
* centry (1)
* execpt (1)
* exsit (1)
* hellworld (1)
* kubect (1)
* stylrcheck (1)
* whaterver (1)
* woring (1)
> fix: various typos

- log/global.go
- log/global_test.go
fix: Ensure thread safety by eliminating lock copy in GetLogger
> fix: return inner Logger from GetLogger for log.WithContext reuse

- contrib/registry/kubernetes/go.mod
- contrib/registry/kubernetes/registry.go
- contrib/registry/kubernetes/registry_test.go
> fix k8s headless service miss namespace

- log/helper.go
- log/helper_test.go
In the real world, some log fields have significant contextual relevance. A reasonable approach is to use `log.With` to attach fields and create a new `Logger`, then convert it to `*log.Helper` held by an object.
For statically created Loggers, this works well; but for dynamically created Loggers, such as when an API request contains a user ID and we perform many operations for it, in order to easily query logs afterwards, we need to include his user ID at each logging point.
Because Service objects generally only contain `*log.Helper`, there is currently no public method to obtain `log.Logger` from `*log.Helper` and add fields, and we have to pass all those fields to every logging point, which is quiet boring.
```go
package kratos
import (
"fmt" …
```
> feat(log): add Logger() method for Helper

- contrib/registry/consul/registry.go
- transport/grpc/resolver/discovery/builder.go
- transport/grpc/resolver/discovery/builder_test.go
使用 Consul 做服务发现时，如果 gRPC Client 的 timeout 设置为 0，程序会报错 `discovery create watcher overtime`。
原因是：
1. gRPC Client 会将 `timeout` 传给 discovery；
https://github.com/go-kratos/kratos/blob/861493a20524217061cf329eff0b4e39fb9cbfeb/transport/grpc/client.go#L190-L196
2. discovery 的 `Build` 会因为 `timeout` 为 0，立马超时，得到 `ErrWatcherCreateTimeout` 的错误。
https://github.com/go-kratos/kratos/blob/861493a20524217061cf329eff0b4e39fb9cbfeb/transport/grpc/resolver/discovery/builder.go#L97-L102
> fix(registry): add timeout validation

- contrib/registry/consul/client.go
- contrib/registry/consul/registry.go
- contrib/registry/consul/registry_test.go
- contrib/registry/consul/service.go
- contrib/registry/consul/watcher.go
修复了一些并发相关的问题：
1. `Registry` 锁的范围太大，比如 `Watch` 对整个函数加锁，不能同时处理多个（不同的）Service；
https://github.com/go-kratos/kratos/blob/5087366d2f90daf8a96bfcab292a433569d46302/contrib/registry/consul/registry.go#L183-L185
2. 相同的 Service 没有共享 `resolve`，只要 `Watch` 就会新开一个 `resolve` 协程；
https://github.com/go-kratos/kratos/blob/5087366d2f90daf8a96bfcab292a433569d46302/contrib/registry/consul/registry.go#L211-L213
3. `Client` 注销任一 Service 都会直接 `cancel` 掉 `Client.ctx`，导致所有的 `heartbeat` 协程退出；
https://github.com/go-kratos/kratos/blob/5087366d2f90daf8a96bfcab292a433569d46302/contrib/registry/consul/client.go#L246-L249
4. 在 `Watch` 时，由于 `w` 先被添加到 `set` 中，然后才会写入 `services event`，如果在两步中间正好遇到之前的 `resolve` 在 `broadcast`，209行的写入则会被卡住（`w` 还没有返回，不会有调用者主动调用 `Next` 消费）。 …
> fix(registry/consul): fix concurrency issues and improve performance

- app.go
- transport/grpc/server.go
- transport/grpc/server_test.go
- transport/http/resolver_test.go
- transport/http/server.go
- transport/http/server_test.go
参考 gRPC 官方示例，当 Server 未能及时优雅退出时，执行强制退出。
https://github.com/grpc/grpc-go/blob/2fd426d0919db7e9e7920e365dd30674c4c9fe90/examples/features/gracefulstop/server/main.go#L89-L100
> fix: Improve server stop handling with graceful shutdowns

- contrib/registry/discovery/discovery.go
optimize loops, when discover load is nil.
> optimize loops, when discover load is nil.

- transport/grpc/server.go
For security reasons, grpc reflection should not be registered directly by default
> feat: disable grpc reflection configuration

- contrib/config/etcd/watcher.go
resp.Err is not a straightforward logical execution; it should be avoided from being executed multiple times.
> perf(contrib/config/etcd): optimize Next method of etcd watcher

- contrib/registry/etcd/registry.go
The code modification is based on two points:  
- It is not recommended to use pointer as key in Go map.
- Changing the service ID to be the key in ctxMap offers better performance. Detailed performance tests will be provided below.
test_kratos_registry.go
```go
package test_kratos_registry
import (
"context"
"testing"
"time"
)
type ServiceInstance struct {
ID        string            `json:"id"`
Name      string            `json:"name"`
Version   string            `json:"version"`
Metadata  map[string]string `json:"metadata"`
Endpoints []string          `json:"endpoints"`
}
type options struct {
ctx       context.Context
namespace string
ttl       time.Duration
maxRetry  int
}
type Registry struct {
opts   *options
ctxMap map[*ServiceInstance]context.CancelFunc
}
func (r *Registry) …
```
> refactor(contrib/registry/etcd): use service ID as Registry.ctxMap key instead of service pointer

- middleware/tracing/tracing_test.go
- transport/http/transport.go
- transport/http/transport_test.go
- Add Response method to Transport interface in transport/http/transport.go
- Implement Response method in Transport struct
- Add test for Response method in transport/http/transport_test.go
- Implement Response method in mockTransport for testing purposes
Example:
HTTP and gRPC server code generated by Protobuf, where HTTP supports file downloads and gRPC retrieves file data.
```proto
syntax = "proto3";
package demo.v1;
import "google/api/annotations.proto";
option go_package = "demo/api/demo/v1;v1";
service Demo {
rpc Download(DownloadReq) returns (DownloadResp) {
option (google.api.http) = {
get : "api/v1/download"
};
}
}
message DownloadReq {
}
message DownloadResp {
bytes data = 1;
}
```
```go
func (s *Service) Download(ctx context.Context, in *v1.DownloadReq) (*v1.DownloadResp, …
```
> feat(transport): add Response method to Transport HTTP

- config/file/format.go
- config/file/format_test.go
`strings.LastIndexByte` offers better performance than `strings.LastIndex`.
> perf(config/env): use strings.LastIndexByte instead of strings.LastIndex
