go-kratos/kratos

- pkg/net/http/blademaster/context.go
> fix http response XSS

- pkg/conf/paladin/default.go
> panic when have not -conf

- doc/wiki-cn/blademaster-quickstart.md
> add bm default router

- .gitignore
- .travis.yml
- doc/wiki-cn/kratos-tool.md
- doc/wiki-cn/protoc.md
- go.mod
- pkg/conf/env/env.go
- pkg/conf/paladin/file_test.go
- pkg/database/tidb/discovery.go
- pkg/ecode/status_test.go
- pkg/log/log.go
- pkg/naming/discovery/discovery.go
- pkg/naming/naming.go
- pkg/net/rpc/warden/client.go
- pkg/net/rpc/warden/internal/examples/grpcDebug/client.go
- pkg/net/rpc/warden/internal/status/status_test.go
- pkg/net/rpc/warden/resolver/direct/direct.go
- pkg/net/rpc/warden/resolver/resolver.go
- pkg/net/rpc/warden/resolver/test/mockdiscovery.go
- pkg/net/rpc/warden/resolver/test/resovler_test.go
- pkg/net/rpc/warden/server_test.go
- tool/kratos/project.go
1.修复kratos new 没去除bm pb依赖；
2.修复naming/discovery为开源版本；
3.修复unit test；
fix #73
> Fix some error

- pkg/net/metadata/metadata.go
- pkg/net/metadata/metadata_test.go
- pkg/net/rpc/warden/client.go
> metadata range

- pkg/conf/paladin/default.go
- pkg/conf/paladin/file.go
- pkg/conf/paladin/map.go
> fix paladin filewatch

- pkg/log/pattern.go
> fix log incorrect source when use pattern render

- pkg/net/rpc/warden/CHANGELOG.md
- pkg/net/rpc/warden/client.go
- pkg/net/rpc/warden/internal/examples/client/client.go
- pkg/net/rpc/warden/resolver/direct/test/direct_test.go
- pkg/net/rpc/warden/server.go
> switch to direct resolver

- pkg/naming/discovery/discovery.go
> valid discovery config

- pkg/net/rpc/warden/CHANGELOG.md
- pkg/net/rpc/warden/balancer/p2c/p2c.go
> add filter for p2c

- doc/wiki-cn/blademaster.md
> fix blademaster doc

- tool/kratos/template.go
> add dao interface

- pkg/cache/memcache/ascii_conn.go
- pkg/cache/memcache/pool_conn.go
- pkg/cache/memcache/util.go
- pkg/cache/memcache/util_test.go
- support read timeout from context
- fix miss prometheus metrics on some method
> update memcache library

- pkg/database/sql/sql.go
> fix: 防止给v强转int时溢出，导致取余结果为负，从而获取到错误的index

- pkg/naming/discovery/discovery.go
> check nil instance

- pkg/net/rpc/warden/client.go
> Register direct resolver for warden

- pkg/naming/discovery/discovery.go
https://github.com/bilibili/discovery/blob/39a50573306aba7c5e1301da9605a8a5bd514eba/naming/client.go#L481
> add every 30 min switch discovery node

- tool/kratos/template.go
refine main.go template following the style in https://gobyexample.com/range-over-channels
> refine main.go template

- doc/wiki-cn/install.md
安装中遇到的一些protobuf的问题，记录一下，其他人可能需要
> add install.md

- doc/wiki-cn/blademaster-mod.md
> Add bm timeout doc

- pkg/cache/metrics.go
- pkg/cache/redis/pool.go
- pkg/naming/discovery/discovery.go
- pkg/net/http/blademaster/perf.go
- pkg/net/http/blademaster/server.go
- pkg/net/rpc/warden/server.go
1. bm perf default use engine port
2. add grpc gzip import
3. fix discovery client register addrs bug
> support some feature and fix some bug and 

- tool/kratos-protoc/protoc.go
- tool/kratos/tool.go
> fix gopath

- tool/kratos/new.go
Add more tips, friendly to new user.
> Tips: please enter a project name you want to create

- doc/wiki-cn/config-paladin.md
> 更新paladin文档

- tool/kratos-protoc/protoc.go
- tool/kratos/tool.go
> improve get gopaths

- tool/kratos/new.go
> fix new path

- .travis.yml
- pkg/net/trace/sample_test.go
ref: https://docs.travis-ci.com/user/docker/#using-docker-compose
> upgrade ci docker compose

- pkg/cache/redis/commandinfo_test.go
- pkg/cache/redis/conn.go
- pkg/cache/redis/conn_test.go
- pkg/cache/redis/log.go
- pkg/cache/redis/main_test.go
- pkg/cache/redis/metrics.go
- pkg/cache/redis/mock.go
- pkg/cache/redis/pipeline.go
- pkg/cache/redis/pipeline_test.go
- pkg/cache/redis/pool.go
- pkg/cache/redis/pool_test.go
- pkg/cache/redis/pubsub_test.go
- pkg/cache/redis/redis.go
- pkg/cache/redis/redis_test.go
- pkg/cache/redis/reply_test.go
- pkg/cache/redis/scan_test.go
- pkg/cache/redis/script_test.go
- pkg/cache/redis/test/docker-compose.yaml
- pkg/cache/redis/trace.go
- pkg/cache/redis/trace_test.go
- pkg/cache/redis/util.go
- pkg/cache/redis/util_test.go
主要更新：
* 完整支持了WithContext，传递ctx；
* 基于ctx完成了redis内部syscall的超时传递；
* 支持了High-Level API Redis（有点类似database/sql.DB），提供了Conn、Close、Do、Pipeline方法
* 支持Pipeline的interface，和使用；
* 其他：优化了代码结构，补全单元测试；
#20
> Redis API优化

- pkg/net/rpc/warden/balancer/wrr/wrr_test.go
> fix balancer test

- doc/wiki-cn/breaker.md
- example/blademaster/middleware/auth/example_test.go
- pkg/database/hbase/metrics.go
- pkg/naming/etcd/etcd_test.go
- pkg/net/http/blademaster/context.go
- pkg/net/ip/ip.go
- pkg/net/netutil/breaker/README.md
- pkg/net/netutil/breaker/breaker.go
- pkg/net/netutil/breaker/breaker_test.go
- pkg/net/netutil/breaker/example_test.go
- pkg/net/rpc/warden/exapmle_test.go
- pkg/net/rpc/warden/internal/benchmark/bench/client/client.go
- pkg/net/rpc/warden/internal/benchmark/helloworld/client/greeter_client.go
- pkg/net/rpc/warden/resolver/direct/test/direct_test.go
- pkg/net/rpc/warden/resolver/test/resovler_test.go
- pkg/net/rpc/warden/server_test.go
- pkg/net/trace/zipkin/zipkin_test.go
- pkg/ratelimit/bbr/bbr.go
- tool/protobuf/pkg/gen/main.go
- tool/protobuf/pkg/utils/stringutils.go
> #206 add breaker doc

- tool/kratos-protoc/bm.go
- tool/kratos-protoc/ecode.go
- tool/kratos-protoc/grpc.go
- tool/kratos-protoc/protoc.go
- tool/kratos-protoc/swagger.go
https://github.com/bilibili/kratos/issues/367
当使用kratos t protoc 不带参数时会扫描当前目录下*.proto文件生成代码
> support *.proto

- go.mod
- go.sum
- pkg/naming/zookeeper/zookeeper.go
zookeeper接入kratos   实现服务注册发现与负载均衡
> zookeeper接入kratos  服务注册发现与负载均衡

- tool/protobuf/pkg/generator/generator.go
https://github.com/bilibili/kratos/issues/408
> remove streaming method

- tool/protobuf/protoc-gen-bswagger/generator.go
https://github.com/bilibili/kratos/issues/417
> fixed swagger method

- pkg/conf/paladin/apollo/apollo.go
> fix apollo validate

- pkg/naming/discovery/discovery.go
> fix concurrent map read and write

- pkg/net/http/blademaster/client.go
- pkg/net/http/blademaster/logger.go
- pkg/net/http/blademaster/metrics.go
- pkg/net/http/blademaster/ratelimit.go
net http metrics add uri method.
> net http metrics add uri method.

- go.mod
modify gopsutil version from v2.19.6 to v2.19.11
> modify gopsutil version from v2.19.6 to v2.19.11

- pkg/database/sql/sql.go
- pkg/database/sql/sql_test.go
> fix parse mysql dsn addr

- pkg/conf/paladin/file.go
- pkg/conf/paladin/file_test.go
> fix for file_test

- doc/wiki-cn/summary.md
> update trace.md links

- tool/protobuf/protoc-gen-bswagger/generator.go
> add validate comment

- pkg/log/dsn.go
- pkg/log/pattern.go
看到 todo 尝试提个 pr，
使用 strings.Builder 替代 log 中使用的 bytes.Buffer
> refine(pkg/log): use strings.Builder instead of bytes.Buffer

- pkg/net/http/blademaster/binding/binding.go
- pkg/net/http/blademaster/binding/default_validator.go
- pkg/net/rpc/warden/validate.go
Add GetValidate func, therefore user can extend validate translations in the future.
> add GetValidate func to get the default validator

- pkg/net/http/blademaster/context.go
- pkg/net/http/blademaster/logger.go
- pkg/net/http/blademaster/server.go
1、fix context Keys map concurrent issue
2、add RemoteIP func to get client ip
3、add context pool
> 【#562】fix context Keys map concurrent issue

- README.md
Windows Install Kratos,Change GO111MODULE to On,Please use 'go env -w GO111MODULE=on'
Fix: GO111MODULE=on -> go env -w GO111MODULE=on
> Update README.md,Fix Windows Install Kratos

- pkg/cache/redis/pool.go
- pkg/cache/redis/redis.go
> feature(#609): add db to config

- pkg/naming/discovery/discovery.go
> fix empty panic

- pkg/net/trace/jaeger/config.go
> 给jaeger加个ENV配置呗

- errors/errors.go
Update comments of `errors.go`.
> Update comments of errors.go

- tool/kratos-protoc/ecode.go
- tool/kratos-protoc/grpc.go
- tool/kratos-protoc/swagger.go
参考 https://github.com/gogo/protobuf 的 “To use proto files from "google/protobuf" you need to add additional args to protoc.”
及 https://github.com/gogo/grpc-example#development 部分
> fix(proto): 使用google定义类时的报错

- pkg/ratelimit/bbr/bbr.go
- pkg/ratelimit/bbr/bbr_test.go
qps较高的情况下`rawMaxPass` 和 `rawMinRT` 被错误的缓存。导致`maxFlight`计算错误。  由于`maxFlight`错误计算可能会导致过度限流的发生。
测试用例为pr中`bbr_test.go`中的`TestBBRMaxPassWithCache`和 `TestBBRMinRtWithCache`。
错误原因：  
```go
rawMaxPass := atomic.LoadInt64(&l.rawMaxPASS)
if rawMaxPass > 0 && l.passStat.Timespan() < 1 {
return rawMaxPass
}
```
以上代码中`l.passStat.Timespan() < 1`根据滑动窗口是否为当前bucket，来判断是否返回缓存值。  
复现步骤：  
1. 已缓存一个`rawMaxPASS`
2. 当前`Timespan()`大于1
3. 调用`rolling_counter`的`Add`方法，此时会新增一个bucket，并更新`lastAppendTime`，详见[rolling_policy.go](https://github.com/go-kratos/kratos/blob/master/pkg/stat/metric/rolling_policy.go#L51)
4. 更新后立即获取的`Timespan() `值为0。 此时程序仍认为缓存未过期，并返回旧的`rawMaxPASS`  
这样在qps较高的情况下`lastAppendTime`会因为`Add`函数的调用不断刷新，导致取得的maxPass始终为一个旧的缓存值。  
缓存对象除了记录缓存的值，还需要记录缓存的时刻。缓存是否过期通过一个类似timespan的方法，判断是否经过了一个bucket的时间。 …
> fix: bbr limiter maxPass minRt cache problem

- cmd/protoc-gen-go-http/go.mod
- cmd/protoc-gen-go-http/go.sum
- cmd/protoc-gen-go-http/http.go
- cmd/protoc-gen-go-http/internal/testproto/echo_service_grpc.pb.go
- cmd/protoc-gen-go-http/internal/testproto/echo_service_http.pb.go
- cmd/protoc-gen-go-http/template.go
- transport/http/client.go
- transport/http/server.go
- transport/http/service.go
- transport/http/service_test.go
http middleware:
-client:
--func(ctx context.Context, req *http.Request) (*http.Response, error)
-server:
--func(ctx context.Context, req *http.Request) (http.ResponseWriter, error)
> fix http middleware

- middleware/metrics/metrics.go
Counter: <kind>_<client/server>_requests_code_total{method, path, code}
Histogram: <kind>_<client/server>_requests_seconds_bucket{method, path}
> add metrics middleware

- middleware/tracing/tracing.go
修复grpc下未初始化opentracing.HTTPHeadersCarrier引起的panic
> repair tracing opentracing.HTTPHeadersCarrier panic

- log/log.go
- log/log_test.go
- log/std.go
- log/std_test.go
- log/wrapper.go
- log/wrapper_test.go
logger := log.Wrap(logrus, fluent)
logger.Print(xxx)
> add logger wrapper

- .github/workflows/go.yml
- log/helper.go
- transport/grpc/context.go
- transport/grpc/server_test.go
- transport/http/context.go
- transport/http/errors.go
- transport/http/service_test.go
> Revert "update workflow"

- transport/grpc/client.go
- transport/grpc/resolver/discovery/resolver.go
> fix resolver

- third_party/validate/README.md
- third_party/validate/validate.proto
PGV: https://github.com/envoyproxy/protoc-gen-validate
> add pgv proto

- cmd/protoc-gen-go-http/template.go
> cmd/protoc-gen-go-http: fix http templates

- transport/http/handle.go
> http: fix encodeError can't write response header

- config/reader.go
> config: fix proto options

- cmd/kratos/internal/project/new.go
- cmd/kratos/internal/project/project.go
Modify the command line tool to specify a custom layout repo when creating a new project
> Modify the command line tool to specify a custom layout repo when creating a new project

- cmd/kratos/main.go
Modify the tool version number as beta3
> Modify the tool version number as beta3

- cmd/kratos/internal/proto/client/client.go
> cmd/kratos: add protoc args

- examples/blog/README.md
> doc: update readme

- examples/helloworld/README.md
- examples/http/README.md
Add readme file for user to show how to use http & hellowrld examples.
> Add README file for http & helloworld examples

- examples/blog/README.md
Delete the content in the readme file that has nothing to do with the blog, and add the guide for users how to run the blog.
> Fix README file of the blog example.

- .github/workflows/codeql-analysis.yml
- remove pull_request, schedule
- remove unnecessary comments
- remove unnecessary strategy and autobuild sections
- add stable branch
> simplify codeql configuration

- errors/errors.go
- errors/errors_test.go
- errors/http.go
- errors/types.go
- errors/types_test.go
- errors/wrap.go
- middleware/status/status.go
- middleware/status/status_test.go
> api/errors: refactor errors

- transport/grpc/server.go
添加grpc 反射注册，项目启动成功之后，可直接使用grpcurl 调用rpc接口
> feat:add grpc reflection register

- middleware/logging/logging.go
fix middleware/logging unable to print params #864
> fix middleware/logging unable to print params #864

- transport/http/binding/proto.go
> transport/http/binding: ignore unexpected field

- config/reader.go
> Fix: marshalJson error, when values contains map[interface{}]interface{}

- app.go
- app_test.go
> kratos: fix: unable to get the correct port when registering the service

- transport/http/handle.go
> transport/http: rename CodecForRequest func

- app.go
- context.go
- internal/context/context.go
- options.go
- transport/grpc/client.go
- transport/grpc/context.go
- transport/grpc/server.go
- transport/grpc/server_test.go
- transport/http/client.go
- transport/http/context.go
- transport/http/server.go
- transport/http/server_test.go
- transport/transport.go
```go
appInfo, ok := kratos.FromContext(req.ctx)
if ok {
appInfo.ID
appInfo.Name
appInfo.Version
}
```
> kratos: add application info

- cmd/kratos/internal/base/repo.go
- cmd/kratos/internal/base/repo_test.go
- cmd/kratos/internal/project/new.go
- cmd/kratos/internal/project/project.go
add cmd specify the version or branch #977
> add cmd specify the version or branch #977

- cmd/kratos/internal/upgrade/upgrade.go
- cmd/protoc-gen-go-errors/go.mod
- cmd/protoc-gen-go-errors/go.sum
- cmd/protoc-gen-go-errors/main.go
- cmd/protoc-gen-go-errors/template.go
> Clean errors

- internal/host/host.go
- transport/grpc/server.go
- transport/grpc/server_test.go
- transport/http/server.go
- transport/http/server_test.go
> transport: fix endpoint extract

- transport/http/context.go
- transport/http/route_test.go
> transport/http: fix content type

- cmd/kratos/main.go
> update kratos version

- log/README.md
fixed log README.md with golang syntax
> golang syntax log README.md

- cmd/kratos/internal/proto/server/template.go
Fix the problem that the service file generated when the proto file contains google.protobuf.empty does not match the expectation。
> Fix cmd proto server

- middleware/tracing/tracing.go
> kratos/typs(trace): the world spelling corrects

- transport/http/server.go
> fix http stop bug

- cmd/kratos/internal/base/get.go
- cmd/kratos/internal/change/change.go
- cmd/kratos/main.go
> feat(cmd): add kratos changelog command

- README.md
- README_zh.md
> docs: update readme, add conventional commits #1096

- README.md
- README_zh.md
- cmd/kratos/internal/base/get.go
- cmd/kratos/internal/change/change.go
- cmd/kratos/internal/run/run.go
- cmd/kratos/main.go
> feat(cmd): add kratos run command and clean code

- examples/http/echo/main.go
> examples: add echo example

- README.md
@tonybase  As described in the title.
> docs: Added a list of acknowledgments that influence on kratos's design.

- README.md
> docs: default documents points to the english document

- examples/config/main.go
> fix(examples): fixed spelling mistake

- transport/http/server.go
- transport/http/server_test.go
transport/http remove duplicate get path code for filter
> style(transport): fix the http server filter, remove duplicate get path code

- config/file/file_test.go
- config/file/watcher.go
Fix a bug in file watcher when the fi is a dir
> <test> config/file: add tests for file watcher 

- examples/registry/etcd/client/main.go
- examples/registry/etcd/server/main.go
- transport/http/client.go
- transport/http/resolver.go
fixed the problem that the node was empty in service discovery, and update demo
> fix(transport/http): fixed the problem of getting empty node list

- log/std.go
> use "and" replace "sub"

- cmd/kratos/internal/project/new.go
- cmd/kratos/internal/project/project.go
Fixed a problem where the full module path could not be specified when creating a project
> fix: fixed kratos  "new" command #1218 

- encoding/form/proto_decode.go
>  http get方法 url 参数带中括号

- config/env/env.go
> Revert "replace env underscore to dot"

- config/env/env.go
- config/env/env_test.go
> fix(env): index out panic when env key is preifix

- transport/http/balancer/random/random.go
- transport/http/calloption.go
> repair some misspelling

- config/env/env.go
- config/env/env_test.go
> fix(config/env): fix env.load() index out of range

- cmd/kratos/internal/proto/client/client.go
cmd proto client: support the third party specify by self and fix the warning when third party is not in current directory
> feat(cmd): support the third party specify by self and fix the warning when third party is not in current directory

- middleware/selector/selector.go
> add selector code annotation

- app.go
> fix endpoint panic

- app_test.go
- examples/go.sum
- options_test.go
- transport/grpc/client_test.go
- transport/grpc/server_test.go
- transport/grpc/transport_test.go
- transport/http/client_test.go
- transport/http/server_test.go
- transport/http/transport_test.go
> test: option tests

- app_test.go
> add appinfo test

- examples/go.mod
- examples/go.sum
- go.mod
- go.sum
upgrade: grpc to 1.39.1
fixes #
> deps: grpc to 1.39.1

- examples/go.mod
- examples/go.sum
- examples/registry/etcd/client/main.go
> fix:etcd<3.13 block question

- README_zh.md
> chore: just fix readme_zh.md

- internal/endpoint/endpoint_test.go
- internal/httputil/http_test.go
> test(internal/) add test

- cmd/kratos/internal/proto/add/template.go
- cmd/kratos/internal/proto/server/template.go
> optimize: template spaces to tabs

- version.go
> fix: edit kratos version

- config/config_test.go
- config/env/env_test.go
- config/options.go
- internal/httputil/http_test.go
> fix(config): replace text with "${}" only

- metrics/README.md
- registry/README.md
> fix: edit registry and metrics readme

- registry/README.md
> fix:update registry's readme

- .github/workflows/go.yml
- .golangci.yml
add some new static check linters for ci workflow:
* deadcode: Finds unused code
* whitespace: Tool for detection of leading and trailing whitespace
* prealloc: Finds slice declarations that could potentially be preallocated
* lll: Reports long lines
* ineffassign: Detects when assignments to existing variables are not used
* goimports: In addition to fixing imports, goimports also formats your code in the same style as gofmt.
* goconst: Finds repeated strings that could be replaced by a constant
* bodyclose: checks whether HTTP response body is closed successfully
* dogsled: Checks assignments with too many blank identifiers (e.g. x, , , _, := f())
* exportloopref: checks for pointers to enclosing loop variables
* unconvert: Remove unnecessary type conversions
* wastedassign: …
> ci: improve golangci static check

- errors/errors.go
将errors包中的Code 和 Reason 方法中
if se := FromError(err); err != nil {
return int(se.Code)
}
修改为
if se := FromError(err); se != nil {
return int(se.Code)
}
> fix(errors): code error

- config/README.md
> fix: update config readme

- .golangci.yml
Adjust gmnd linter options
more info:
gomnd: https://github.com/tommy-muehle/go-mnd/#checks
golangci-lint: https://golangci-lint.run/usage/configuration/
> ci: adjust magic number check

- transport/http/server_test.go
fix a potential panic problem while running test.
PTAL~
> test(transport/http):fix nil problem

- examples/metrics/main.go
> fix change unit to seconds

- metrics/README.md
> fix metrics readme

- app.go
fix:reuse parent ctx  cause  unexpected stop of App
> fix:reuse parent ctx cause unexpected stop of App

- cmd/protoc-gen-go-errors/errors.go
- cmd/protoc-gen-go-errors/template.go
- hack/.lintcheck_failures
> Fix lint of files in cmd/protoc-gen-go-errors

- README.md
- README_zh.md
…cation
switch to go install according to golang.org/doc/go-get-install-deprecation
fixes #1439
> docs: Use go install when install kratos instead of go get

- cmd/protoc-gen-go-http/http.go
- cmd/protoc-gen-go-http/template.go
- hack/.lintcheck_failures
> fix: Fix lint of files in cmd/protoc-gen-go-http

- balancer/node.go
- balancer/selector.go
- balancer/selector/p2c/p2c.go
- balancer/selector/random/random.go
> optimization

- transport/http/server.go
> fix http server handler

- balancer/selector/p2c/p2c.go
> fix:node block and done panic

- transport/http/server.go
HTTP server support HandleHeader
fixes #
> feat: add http header handler

- transport/grpc/server.go
- transport/http/server.go
> fix: optimizate with context

- config/README.md
> fix:edit the config's readmes

- transport/grpc/server.go
- transport/grpc/server_test.go
> fix(transport/grpc): default base ctx

- transport/http/server_test.go
> add test for HandleHeader

- go.mod
> fix:remove x/net package

- internal/host/host.go
- internal/host/host_test.go
> fix(internal/host): fix bug of host.Extract

- transport/http/server_test.go
> fix(transport/http): defer leak in test

- config/file/file_test.go
> fix(config/file): fix error in file test

- transport/grpc/server.go
- transport/grpc/server_test.go
The HTTP server has an Endpoint option, but gRPC does not, which leads to inconsistent user experience. So, add Endpoint option to gRPC server.
fixes #
> feat(transport/grpc): add endpoint option in grpc server

- .github/workflows/go.yml
- config/env/env_test.go
- hack/tools.sh
- middleware/tracing/span_test.go
- middleware/tracing/tracing_test.go
unit test enhanced
* update go version to 1.17
* use t.Setenv instead of os.Setenv
* enhance tracing test
> test(middleware/tracing): tracing unit test enhancement

- transport/grpc/server.go
- transport/grpc/server_test.go
> fix:server start panic when use Endpoint

- transport/http/resolver_test.go
fix http resvoler http test case
> fix http resvoler http test case

- log/README.md
> chore: fix doc error

- examples/selector/client/main.go
- examples/selector/server/main.go
- selector/default.go
- selector/p2c/p2c.go
- selector/random/random.go
- selector/wrr/wrr.go
- transport/grpc/balancer.go
- transport/grpc/client.go
- transport/grpc/client_test.go
- transport/grpc/transport.go
- transport/http/client.go
feat: add selector and filters examples
> feat: add selector and filters examples

- README.md
- README_zh.md
- ROADMAP.md
> feat:edit readme and roadmap

- contrib/registry/etcd/registry.go
- contrib/registry/etcd/watcher.go
> fix:etcd prefix find error

- contrib/metrics/datadog/counter.go
- contrib/metrics/datadog/gauge.go
- contrib/metrics/datadog/observer.go
- hack/.lintcheck_failures
part of #1430
Other special notes for reviewer:
> fix: contrib metrics datadog lint err

- contrib/registry/discovery/go.sum
- examples/go.sum
> fix: fix registry go mod

- cmd/protoc-gen-go-http/http.go
> feat:add warning when http path filed use map or list

- middleware/auth/jwt/jwt.go
'tokenInfo' might have 'nil' or other unexpected value as its corresponding error variable might be not 'nil'
> fix: 'tokenInfo' might have 'nil' or bad value

- contrib/registry/consul/client.go
- contrib/registry/consul/registry.go
- contrib/registry/consul/watcher.go
- hack/.lintcheck_failures
> fix: consul lint error

- cmd/kratos/internal/base/repo.go
- cmd/kratos/internal/project/project.go
> fix(cmd/kratos): use context timeout control, add timeout param

- middleware/recovery/recovery.go
Recovery logger with context
fixes #
> feat: recovery logger with ctx

- selector/node/direct/direct.go
- selector/node/ewma/node.go
> feat: export selector node

- selector/p2c/p2c_test.go
> fix: fix p2c test

- contrib/encoding/msgpack/go.sum
- contrib/encoding/msgpack/msgpack.go
- contrib/registry/kubernetes/registry.go
- contrib/registry/nacos/registry.go
- contrib/registry/nacos/watcher.go
- contrib/registry/zookeeper/register.go
- contrib/registry/zookeeper/register_test.go
- contrib/registry/zookeeper/watcher.go
- examples/go.sum
- hack/.lintcheck_failures
**Description (what this PR does / why we need it):**
fix k8s nacos and zookeeper registry lint
**Which issue(s) this PR fixes (resolves / be part of):**
part of [#1430](https://github.com/go-kratos/kratos/issues/1430)
**Other special notes for reviewer:**
> fix: fix k8s nacos and zookeeper registry lint

- examples/http/README.md
> Modify the README.md of http package. Make the output of gin example consistent with the code.

- selector/balancer.go
- selector/default_selector.go
- selector/node/direct/direct.go
- selector/node/direct/direct_test.go
- selector/node/ewma/node.go
- selector/selector_test.go
- transport/grpc/balancer.go
return raw node to improve performance
> feat: add raw node

- cmd/protoc-gen-go-http/http.go
> fix(cmd/http): fixed cannot declare a route with a regular expression

- .github/workflows/go.yml
- contrib/config/consul/README.md
- contrib/config/kubernetes/README.md
- contrib/config/nacos/README.md
- contrib/config/nacos/config_test.go
- contrib/config/nacos/go.mod
- contrib/config/nacos/go.sum
- contrib/registry/discovery/README.md
- contrib/registry/nacos/README.md
- contrib/registry/nacos/go.mod
- contrib/registry/nacos/go.sum
- contrib/registry/nacos/registry_test.go
- contrib/registry/nacos/watcher.go
- examples/go.mod
- examples/go.sum
- go.sum
contrib:
add README, these file should be completed
add test
> test: add nacos test

- contrib/config/nacos/config_test.go
- contrib/registry/nacos/registry_test.go
fix nacos registry test data race
fixes #
> fix: fix nacos registry test data race

- selector/default_node.go
- selector/default_selector.go
- selector/filter/version.go
- selector/node/ewma/node.go
- selector/p2c/p2c.go
- selector/random/random.go
- selector/selector.go
- selector/wrr/wrr.go
> fix:modify annotation and wrong words

- middleware/tracing/tracer.go
> fix(middleware/tracing):  modify kartos to kratos

- contrib/config/apollo/README.md
- contrib/registry/discovery/README.md
replenish `contrib` modules' documents
fixes #1605
> docs: replenish config/apollo and registry/discovery readme

- contrib/config/etcd/README.md
`contrib/config/etcd`  add README file
#1605
> docs: add etcd config doc

- contrib/registry/consul/client.go
- examples/registry/consul/server/main.go
> fix:add consul all health check

- examples/registry/nacos/client/main.go
> 修复了examples/registry/nacos/client中grpc调用的错误

- contrib/config/nacos/config_test.go
- contrib/registry/nacos/watcher.go
- transport/grpc/resolver/discovery/builder.go
> optimize:chan bool to chan struct{}

- app.go
> feat(app): app info delivery to stop context

- examples/selector/client/main.go
- selector/default_selector.go
- selector/filter.go
- selector/filter/version.go
- selector/options.go
- selector/selector_test.go
- transport/grpc/balancer.go
- transport/grpc/balancer_test.go
- transport/grpc/client.go
- transport/grpc/transport.go
feat:balancer revert to select filters
> feat:balancer revert to select filters

- contrib/registry/nacos/registry.go
- contrib/registry/nacos/watcher.go
与java的dubbo框架写的grpc服务集成，元数据缺失kind字段信息也能正常访问
fixes #
> feat(registry/nacos): add default kind option

- contrib/registry/nacos/registry.go
> fix: fix nacos.Register many endpoint metadata kind error

- cmd/kratos/internal/proto/add/add.go
> chore: completion command  in the comment

- contrib/registry/nacos/README.md
- contrib/registry/nacos/registry.go
If si.Metadata is nil,  reduce twice string copies
> registry/nacos: reduce twice string copies

- middleware/selector/selector.go
- middleware/selector/selector_test.go
Fix context not being passed correctly(BREAKCHANGE):
```
MatchFunc   func(operation string) bool
-> 
MatchFunc   func(ctx context.Context, operation string) bool
```
> feat: middleware seletor add ctx match

- contrib/registry/consul/client.go
- contrib/registry/consul/registry.go
add endpoints resolver option
fixes #
> consul: support WithServiceResolver option

- transport/grpc/client.go
- transport/grpc/client_test.go
> feat(transport/grpc): gRPC client discovery supports incoming logger and timeout

- cmd/kratos/version.go
- cmd/protoc-gen-go-errors/version.go
- cmd/protoc-gen-go-http/go.mod
- cmd/protoc-gen-go-http/go.sum
- cmd/protoc-gen-go-http/version.go
- contrib/config/apollo/go.mod
- contrib/config/consul/go.mod
- contrib/config/etcd/go.mod
- contrib/config/kubernetes/go.mod
- contrib/config/nacos/go.mod
- contrib/encoding/msgpack/go.mod
- contrib/log/fluent/go.mod
- contrib/log/zap/go.mod
- contrib/metrics/datadog/go.mod
- contrib/metrics/prometheus/go.mod
- contrib/registry/consul/go.mod
- contrib/registry/discovery/go.mod
- contrib/registry/etcd/go.mod
- contrib/registry/kubernetes/go.mod
- contrib/registry/nacos/go.mod
- contrib/registry/zookeeper/go.mod
- examples/go.mod
- version.go
> deps: update kratos version to 2.1.3

- cmd/protoc-gen-go-http/go.mod
- cmd/protoc-gen-go-http/go.sum
golang/go#44840
golang/go#40276
> fix(cmd/proto-gen-http-go): remove go.mod replace

- pkg/net/http/blademaster/binding/binding.go
Compatible with Content-type: text/json when the request is in json format
fixes #
> Compatible with Content-type: text/json when the request is in json

- cmd/kratos/internal/proto/client/client.go
- cmd/kratos/internal/upgrade/upgrade.go
- examples/blog/openapi.yaml
- third_party/google/api/client.proto
- third_party/google/api/field_behavior.proto
> feat(cmd/kratos): generating API documentation using Gnostic

- cmd/protoc-gen-go-http/http.go
- cmd/protoc-gen-go-http/http_test.go
This PR is a continuation of https://github.com/go-kratos/kratos/pull/1704, to fix https://github.com/go-kratos/kratos/issues/1653. When the path was `"/v1/{parent=shelves/*}/books"` the matching path was `"/v1/{parent:shelves/*}"` instead of `"/v1/{parent:shelves/*}/books"` so it was matching any URL including `/shelves/*` and not only those with `/shelves/*/book`
fixes # https://github.com/go-kratos/kratos/issues/1653
> fix(cmd/protoc-gen-go-http): Fix when replacement rule is not ending

- transport/grpc/server.go
- transport/grpc/server_test.go
- transport/http/server.go
> feat(transport):add grpc and http with listen

- examples/go.mod
- examples/go.sum
- examples/registry/etcd/cmuxServer/main.go
> feat(examples/):add etcd registry cmux example

- contrib/registry/consul/client.go
- contrib/registry/consul/registry.go
- contrib/registry/consul/registry_test.go
Add WithHeartbeat option, so user can choose healthcheck or heartbeat, or both.
fixes #
> feat(registry/consul): add WithHeartbeat option

- errors/errors.go
optimize error , return value of FromError function is Never empty.
> optimization: optimize error

- errors/errors_test.go
- errors/types_test.go
- errors/wrap_test.go
> test(errors): add errors test

- .github/workflows/gitee-sync.yml
use github actions to sync the latest main branch to gitee https://gitee.com/go-kratos/kratos
> ci: sync to gitee automation

- log/README.md
> readme:add log third party log library readme

- .github/workflows/gitee-sync.yml
> feat:sync to gitee where release a version

- contrib/registry/zookeeper/register.go
> fix: ZK registration not cleanup after application exit

- cmd/kratos/internal/base/path.go
> fix(cmd/kratos): filepath walk nil pointer reference problem

- log/value.go
> fix:fix log caller error

- transport/grpc/server.go
fixed the problem that grpc stop could not close properly.
> fix(transport/grpc): fixed the problem that grpc stop could not close properly

- contrib/config/consul/README.md
> docs: incorrect consul of the config doc

- contrib/registry/consul/client.go
… socket connection failed ... too many colons in address]
解决consul client以IPv6地址格式register consul server health check时报错:[Check socket connection failed ... too many colons in address]问题
fixes #
> fix the consul health check for IPv6 support

- .golangci.yml
- contrib/config/apollo/watcher.go
- hack/.lintcheck_failures
> fix: fix ci tool

- examples/http/redirect/main.go
> feat:add examples redirect url

- contrib/registry/kubernetes/registry.go
Currently the k8s registry cannot implement `registry.Discovery` interface.
This PR updates the k8s registry to follow the `registry.Discovery` interface.
> fix: k8s discovery interface

- contrib/config/consul/config.go
Skip the empty key. fix #1829 .
> fix(config/consul):Config from consul skip empty key

- encoding/README.md
- log/README.md
- registry/README.md
> update contrib readme

- cmd/kratos/version.go
- cmd/protoc-gen-go-errors/version.go
- cmd/protoc-gen-go-http/version.go
- contrib/config/apollo/go.mod
- contrib/config/consul/go.mod
- contrib/config/etcd/go.mod
- contrib/config/kubernetes/go.mod
- contrib/config/nacos/go.mod
- contrib/encoding/msgpack/go.mod
- contrib/log/aliyun/go.mod
- contrib/log/fluent/go.mod
- contrib/log/zap/go.mod
- contrib/metrics/datadog/go.mod
- contrib/metrics/prometheus/go.mod
- contrib/registry/consul/go.mod
- contrib/registry/discovery/go.mod
- contrib/registry/etcd/go.mod
- contrib/registry/kubernetes/go.mod
- contrib/registry/nacos/go.mod
- contrib/registry/polaris/go.mod
- contrib/registry/zookeeper/go.mod
- examples/go.mod
- version.go
> deps: upgrade kratos version to 2.2.0

- contrib/registry/polaris/registry.go
- contrib/registry/polaris/registry_test.go
Discovery Tencent Polaris
register pull request is merged
fixes #1685
> Discovery For Tencent Polaris

- examples/transaction/ent/Makefile
> feat(example/transaction/ent): add ent install in Makefile

- app.go
> perf(app): add prealloc

- cmd/protoc-gen-go-http/http.go
- contrib/config/etcd/config.go
- examples/blog/internal/data/article.go
> perf: add prealloc

- .github/semantic.yml
> feat: add semantic.yml

- app.go
Fix wrong graceful shutdown
fixes https://github.com/go-kratos/kratos/issues/1856
> fix graceful shutdown

- cmd/protoc-gen-go-http/http.go
> fix(cmd): proto-gen-go-http warn only when ending with a slash

- .github/semantic.yml
> fix: update semantic

- log/filter.go
- log/filter_test.go
fixes # https://github.com/go-kratos/kratos/issues/1897
> fix(log): FilterFunc keyvals lost logger prefix

- contrib/log/aliyun/go.mod
- contrib/log/aliyun/go.sum
> fix(log): Improper Input Validation in GoGo Protobuf CVE-2021-3121

- contrib/opensergo/opensergo.go
> fix(contrib/opensergo): fix index error

- encoding/form/form_test.go
- encoding/form/proto_decode.go
It can not decode  the correct URL  from base64.URLEncoding
> feat: decode google.protobuf.BytesValue compatible base64.URLEncoding.

- transport/http/resolver.go
- transport/http/resolver_test.go
fix unexpected overriding behavior when return an error
fixes #1881
> fix:(transport/http): fix unexpected overriding behavior when return an error

- config/value.go
use kratos with watch apollo config.
add a new config item in apollo server,after publish ,kartos config watch works,but UnmarshalOptions.DiscardUnknown default is false,so scan will failed.
> feat: Added ability to configure protojson

- contrib/registry/zookeeper/go.mod
- contrib/registry/zookeeper/go.sum
- contrib/registry/zookeeper/register.go
- contrib/registry/zookeeper/register_test.go
- contrib/registry/zookeeper/service.go
- contrib/registry/zookeeper/watcher.go
fixes/zookeeper #1966 
Zookeeper Registry 的 New 函数签名被重写了
> feat(registry): zookeeper watch node changed

- cmd/protoc-gen-go-errors/errors.go
> fix:fix error camel case

- log/global.go
- log/global_test.go
> feat:add context for log

- config/reader.go
> feat: add config log

- config/config.go
- config/config_test.go
- config/options.go
- config/reader.go
- contrib/config/apollo/README.md
- contrib/config/apollo/apollo.go
- contrib/config/apollo/watcher.go
- contrib/registry/discovery/README.md
- contrib/registry/discovery/discovery.go
- contrib/registry/discovery/impl_registrar.go
- contrib/registry/kubernetes/go.mod
- contrib/registry/kubernetes/go.sum
- log/global.go
- log/value.go
- middleware/recovery/recovery.go
- middleware/recovery/recovery_test.go
- transport/grpc/client.go
- transport/grpc/client_test.go
- transport/grpc/resolver/discovery/builder.go
- transport/grpc/resolver/discovery/builder_test.go
- transport/grpc/resolver/discovery/resolver.go
- transport/grpc/resolver/discovery/resolver_test.go
- transport/grpc/server.go
- transport/grpc/server_test.go
- transport/http/resolver.go
- transport/http/server.go
> log: remove component logger to use global logger

- transport/http/codec.go
- transport/http/redirect.go
- transport/http/redirect_test.go
```go
return http.NewRedirect(url, code)
```
> transport/http(feat): add redirector to forward request

- internal/endpoint/endpoint.go
- internal/endpoint/endpoint_test.go
- transport/grpc/resolver/discovery/resolver.go
- transport/grpc/server.go
- transport/http/resolver.go
- transport/http/server.go
> feat: make secure url to grpcs://127.0.0.1/

- cmd/kratos/version.go
- cmd/protoc-gen-go-errors/version.go
- cmd/protoc-gen-go-http/version.go
- contrib/config/apollo/go.mod
- contrib/config/consul/go.mod
- contrib/config/etcd/go.mod
- contrib/config/kubernetes/go.mod
- contrib/config/nacos/go.mod
- contrib/encoding/msgpack/go.mod
- contrib/log/aliyun/go.mod
- contrib/log/fluent/go.mod
- contrib/log/zap/go.mod
- contrib/metrics/datadog/go.mod
- contrib/metrics/prometheus/go.mod
- contrib/opensergo/go.mod
- contrib/registry/consul/go.mod
- contrib/registry/discovery/go.mod
- contrib/registry/etcd/go.mod
- contrib/registry/kubernetes/go.mod
- contrib/registry/nacos/go.mod
- contrib/registry/polaris/go.mod
- contrib/registry/zookeeper/go.mod
- version.go
> deps: upgrade kratos version to v.2.3.1

- transport/http/codec.go
Add the Flusher type for Flush case
> Add Flusher type alias  .

- transport/http/codec.go
Content-type is not be promise from RFC2616 7.2.1.
it may be need a clear describe info:)
> optimization: optimize a clear interaction for content-type

- .github/pull_request_template.md
> doc: update pull request template

- cmd/protoc-gen-go-http/template.go
add http operation constant 方便外部引用和比较
> feat: add http operation const

- selector/default_selector.go
- selector/peer.go
- selector/peer_test.go
- transport/grpc/client.go
- transport/http/client.go
> feat: add peer for selector

- cmd/kratos/internal/proto/add/add.go
- cmd/kratos/internal/proto/add/add_test.go
fix: #2089 
`kratos proto add hello/hello_world.proto`
```protobuf
syntax = "proto3";
package hello;
option go_package = "/hello;hello";
option java_multiple_files = true;
option java_package = "hello";
service HelloWorld {
rpc CreateHelloWorld (CreateHelloWorldRequest) returns (CreateHelloWorldReply);
rpc UpdateHelloWorld (UpdateHelloWorldRequest) returns (UpdateHelloWorldReply);
rpc DeleteHelloWorld (DeleteHelloWorldRequest) returns (DeleteHelloWorldReply);
rpc GetHelloWorld (GetHelloWorldRequest) returns (GetHelloWorldReply);
rpc ListHelloWorld (ListHelloWorldRequest) returns (ListHelloWorldReply);
}
message CreateHelloWorldRequest {}
message CreateHelloWorldReply {}
message UpdateHelloWorldRequest {}
message UpdateHelloWorldReply {}
message DeleteHelloWorldRequest {}
message …
```
> fix:fix proto add underscore problem

- config/config.go
- contrib/config/apollo/watcher.go
- contrib/config/consul/watcher.go
- contrib/config/etcd/watcher.go
- contrib/config/nacos/config.go
- add `config.ErrWatcherStopped error`
- return on watcher.Next() after Watcher.Stop()
> feat(config): add ErrorWatcherStopped and return on watcher.Next() after Watcher.Stop()

- .github/workflows/go.yml
> use offical image

- cmd/protoc-gen-go-http/template.go
fix:duplicate  generation const for http
> fix:duplicate  generation const for http

- api/metadata/server.go
> fix: allow the case of proto not found, such like gogo.proto

- encoding/form/proto_encode.go
> fix: repair url ptr not encode

- contrib/log/zap/zap.go
- contrib/log/zap/zap_test.go
- contrib/registry/zookeeper/register_test.go
coverage: 90+% of statements
part of #2135
> test(contrib): add unit test for zap_test.go & register_test.go

- contrib/log/fluent/fluent_test.go
coverage: 90+% of statements
part of https://github.com/go-kratos/kratos/issues/2135
> test(contrib): add unit test for fluent.go

- contrib/registry/consul/registry_test.go
add unit test for contrib/registry/consul
part of #2135
> test(contrib): add unit test for contrib/registry/consul

- contrib/config/kubernetes/config_test.go
coverage: 90+% of statements
part of #2135
> test(contrib): add unit test for contrib/config/k8s

- cmd/kratos/internal/proto/server/template.go
> fix: typo on emptypb.Empty

- contrib/config/nacos/config.go
- contrib/config/nacos/config_test.go
- contrib/config/nacos/go.mod
- contrib/registry/nacos/registry_test.go
**Description (what this PR does / why we need it):**
add nacos unit test
**Which issue(s) this PR fixes (resolves / be part of):**
part of [#2135](https://github.com/go-kratos/kratos/issues/2135)
Other special notes for the reviewers:
> feat(contrib): add nacos unit test and remove unused function

- metadata/metadata_test.go
supplement the unit testing of metadata
part of #2147
> test: supplement the unit testing of metadata

- contrib/registry/kubernetes/go.sum
- contrib/registry/kubernetes/registry_test.go
coverage: 90+% of statements
part of https://github.com/go-kratos/kratos/issues/2135
> test(contrib): add unit test for contrib/registry/k8s

- config/file/format_test.go
add  tests for config/file/format
part of #2147
> test(config/file): add format test (#2147)

- errors/errors.go
> fix(errors): panic when err of Clone is nil

- api/metadata/server.go
It skips the service from the service list (metadata call) instead of failing with error if one of the service's dependencies is not found
> feat(metadata): Ignore service if the dependencies are not found

- errors/errors_test.go
> test(errors): improve coverage

- contrib/config/consul/config_test.go
add unit test for contrib/config/consul
part of #2135
> test(contrib/config/consul): add unit test for contrib/config/consul

- contrib/metrics/prometheus/counter_test.go
- contrib/metrics/prometheus/gauge_test.go
- contrib/metrics/prometheus/go.mod
- contrib/metrics/prometheus/histogram_test.go
- contrib/metrics/prometheus/summary_test.go
add unit test for contrib/metrics/prometheus
part of #2135
> test(contrib): add unit test for contrib/metrics/prometheus

- contrib/registry/eureka/client.go
- contrib/registry/eureka/register.go
- contrib/registry/kubernetes/registry.go
> style(contrib/registry/*) annotation perfect

- cmd/kratos/version.go
- cmd/protoc-gen-go-errors/version.go
- cmd/protoc-gen-go-http/version.go
- contrib/config/apollo/go.mod
- contrib/config/consul/go.mod
- contrib/config/etcd/go.mod
- contrib/config/kubernetes/go.mod
- contrib/config/nacos/go.mod
- contrib/config/polaris/go.mod
- contrib/config/polaris/go.sum
- contrib/encoding/msgpack/go.mod
- contrib/log/aliyun/go.mod
- contrib/log/fluent/go.mod
- contrib/log/logrus/go.mod
- contrib/log/zap/go.mod
- contrib/metrics/datadog/go.mod
- contrib/metrics/prometheus/go.mod
- contrib/opensergo/go.mod
- contrib/registry/consul/go.mod
- contrib/registry/discovery/go.mod
- contrib/registry/etcd/go.mod
- contrib/registry/kubernetes/go.mod
- contrib/registry/nacos/go.mod
- contrib/registry/polaris/go.mod
- contrib/registry/zookeeper/go.mod
- version.go
> deps: upgrade kratos version to v2.4.0

- README_zh.md
> doc: update README_zh.md

- contrib/log/logrus/logrus.go
- contrib/log/logrus/logrus_test.go
fix contrib logrus add fatal level
> fix(contrib): add logrus fatal level

- cmd/kratos/internal/project/add.go
> fix: remove unuseful file when use nomod

- contrib/registry/zookeeper/register.go
The current registrar with zookeeper will re-connected when bad connection and so on.
But the data node info will not re-register. It makes no sense.
This pr provides reRegister function with a goroutine support that app can auto recovery and re-register with registrar.
> fix: zookeeper add auto re-register

- transport/grpc/codec.go
> fix(grpc/codec): fix default behavior for gRPC encoding

- internal/matcher/middleware.go
- internal/matcher/middleware_test.go
- transport/grpc/interceptor.go
- transport/grpc/server.go
- transport/grpc/server_test.go
- transport/http/context.go
- transport/http/server.go
- transport/http/server_test.go
```go
// Use uses a service middleware with selector.
// selector:
//   - '/*'
//   - '/helloworld.v1.Greeter/*'
//   - '/helloworld.v1.Greeter/SayHello'
srv := http.NewServer()
srv.Use("/v1/users/*", Auth)
```
> feat(middleware): add selector matcher

- .gitignore
Update gitignore file for go workspace. [Reference](https://github.com/github/gitignore/blob/main/Go.gitignore#L20-L21
)
> update ignore for go workspace

- cmd/kratos/version.go
- cmd/protoc-gen-go-errors/version.go
- cmd/protoc-gen-go-http/version.go
- contrib/encoding/msgpack/go.mod
- contrib/log/aliyun/go.mod
- contrib/log/fluent/go.mod
- contrib/log/logrus/go.mod
- contrib/log/zap/go.mod
- contrib/metrics/datadog/go.mod
- contrib/metrics/prometheus/go.mod
- contrib/opensergo/go.mod
- contrib/registry/consul/go.mod
- contrib/registry/discovery/go.mod
- contrib/registry/etcd/go.mod
- contrib/registry/kubernetes/go.mod
- contrib/registry/nacos/go.mod
- contrib/registry/polaris/go.mod
- contrib/registry/zookeeper/go.mod
- version.go
> deps: upgrade kratos version to v2.4.1

- contrib/registry/zookeeper/register.go
The nodes will not be re-created when app is not correct shutdown(client is not cleanup and close zk connection).
The wrong nodes will be exists a few time until auto-deleted by zookeeper server when elder session expired.
This pr makes zookeeper ephemeral nodes handling after restart.
Fixes a race condition if the server crashes without using CreateProtectedEphemeralSequential().
More infomation: https://blog.karatos.in/a?ID=01150-a246c602-55f4-4a15-991c-5415f379d59e.
> fix(registry): contrib/registry/zookeeper ephemeral nodes handling after restart

- .github/workflows/go.yml
- README.md
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>
the latest nacos-server image has an bug that it will fail to startup. so I set the old version to it.
> fix(chore): set nacos-server v2.1.0 and consul v1.12.3

- contrib/registry/consul/registry.go
> feat(registry): consul get service support remote 

- log/log.go
> fix(log): wrong order of Logger prefix kvs

- contrib/config/apollo/apollo.go
- contrib/config/apollo/parser.go
- contrib/config/apollo/watcher.go
> bc: apollo unable to get and watch to the properties file

- cmd/kratos/version.go
- cmd/protoc-gen-go-errors/version.go
- cmd/protoc-gen-go-http/version.go
- contrib/encoding/msgpack/go.mod
- contrib/log/aliyun/go.mod
- contrib/log/fluent/go.mod
- contrib/log/logrus/go.mod
- contrib/log/tencent/go.mod
- contrib/log/tencent/go.sum
- contrib/log/zap/go.mod
- contrib/metrics/datadog/go.mod
- contrib/metrics/prometheus/go.mod
- contrib/opensergo/go.mod
- contrib/registry/consul/go.mod
- contrib/registry/discovery/go.mod
- contrib/registry/etcd/go.mod
- contrib/registry/kubernetes/go.mod
- contrib/registry/nacos/go.mod
- contrib/registry/polaris/go.mod
- contrib/registry/zookeeper/go.mod
- version.go
> deps: upgreade kratos version to v2.5.0

- internal/endpoint/endpoint.go
- internal/endpoint/endpoint_test.go
> fix: delete endpoint service discovery compatibility

- transport/http/context.go
fix typo in transport/http/context.go
> fix typo in transport/http/context.go

- README.md
Found some grammar mistakes in the Readme.md file along with some sentences that don't feel smooth to read. This pull request fixed them.
> fix grammar problems in the Readme file

- app.go
add notes by wg.Done() not used defer
> add notes by wg.Done() not used defer

- contrib/registry/consul/client.go
- contrib/registry/consul/registry.go
> feat(registry): consul support user custom checks

- selector/selector_test.go
> test(selector): improve coverage

- README.md
> docs: update readme.md, remove qq group

- transport/grpc/client.go
- transport/http/client.go
> fix: init global selector to wrr

- config/env/env.go
- config/env/env_test.go
prefixs -> prefixes
[dict](https://cn.bing.com/dict/prefix.)
> style(config/env): prefixs -> prefixes

- cmd/kratos/internal/proto/add/add.go
> fix(cmd): fix CmdAdd long message example

- contrib/config/etcd/config_test.go
Added test cases for the about etcd method
- WithPath(path string)
- WithPrefix(prefix bool)
Update #2135
> test(config): add etcd config method test

- cmd/kratos/internal/change/get_test.go
https://github.com/go-kratos/kratos/issues/2147
> test(cmd/change): add ParseGithubURL test

- cmd/kratos/internal/base/mod_test.go
https://github.com/go-kratos/kratos/issues/2147
> test(cmd): add ModulePath test

- cmd/kratos/internal/change/get.go
> feat(cmd): user prePage to check changelog dev length

- internal/host/host.go
> feat(internal/host):prefer ipv4 than ipv6

- .gitignore
> cleanup: `.gitignore` remove repeated `.*so`

- .github/ISSUE_TEMPLATE/feature-request.md
- CONTRIBUTING.md
- cmd/protoc-gen-go-http/http.go
- contrib/config/etcd/README.md
- contrib/log/aliyun/aliyun.go
- contrib/metrics/datadog/options.go
- contrib/registry/consul/client.go
- contrib/registry/discovery/discovery.go
- contrib/registry/etcd/registry.go
- contrib/registry/eureka/eureka.go
- contrib/registry/eureka/register.go
- contrib/registry/kubernetes/registry.go
- encoding/encoding_test.go
- encoding/form/proto_decode.go
- errors/types.go
- internal/group/group.go
- log/global_test.go
- log/helper_writer.go
- middleware/circuitbreaker/circuitbreaker.go
- middleware/logging/logging.go
- middleware/metadata/metadata_test.go
- middleware/tracing/span.go
- registry/registry.go
- selector/random/random.go
- selector/selector_test.go
- transport/grpc/balancer.go
- transport/http/client.go
- transport/http/filter.go
- transport/http/status/status.go
fix grammar
an HTTP: https://zh.hinative.com/questions/19555969
> fix: grammar problems

- encoding/form/form.go
- encoding/form/proto_encode.go
- transport/http/binding/encode.go
- transport/http/binding/encode_test.go
> fix(http/binding): fix http encode url

- contrib/registry/consul/client.go
> fix(registry/consul): use health check option to control custom checks

- selector/default_node.go
- selector/default_selector.go
- selector/node/direct/direct.go
- selector/node/ewma/node.go
> fix(selector): modify interface check way

- contrib/registry/servicecomb/registry.go
> cleanup: remove the repeated import

- app_test.go
- contrib/registry/nacos/registry.go
- middleware/circuitbreaker/circuitbreaker_test.go
- middleware/validate/validate_test.go
- transport/grpc/resolver/direct/builder_test.go
- transport/http/client_test.go
- transport/http/context_test.go
- transport/http/resolver_test.go
- transport/http/server_test.go
static err should use `errors.New`, the performance will be higher than `fmt.Errorf`
reference: https://github.com/uber-go/guide/blob/master/style.md#errors
> cleanup: remove fmt and errors new err

- config/value.go
optimize atomicValue format string func
> style(config/value): optimize atomicValue format string

- contrib/registry/etcd/registry.go
- contrib/registry/eureka/register.go
- log/global_test.go
- middleware/tracing/span.go
declare an empty slice to var s []int replace s :=[]int{}, https://github.com/golang/go/wiki/CodeReviewComments#declaring-empty-slices
> style: modify declaring empty slices

- .github/workflows/go.yml
> support 1.19 unit tests.

- contrib/log/aliyun/aliyun.go
- contrib/log/aliyun/aliyun_test.go
- contrib/log/tencent/tencent.go
> chore(log): let log toString same

- .golangci.yml
- api/metadata/server.go
- config/file/file_test.go
- config/value_test.go
- contrib/config/consul/config.go
- contrib/log/aliyun/aliyun.go
- contrib/log/tencent/tencent.go
- encoding/form/proto_encode.go
- encoding/xml/xml_test.go
remove redundancy type conversion
> cleanup: remove redundancy type conversion and golangci add unconvert

- .golangci.yml
- contrib/registry/servicecomb/registry.go
- contrib/registry/servicecomb/registry_test.go
- contrib/registry/servicecomb/watcher.go
- transport/http/binding/encode.go
Static check import order, PR: #2379
> feat: golangci add goimports local-prefixes

- contrib/registry/consul/registry.go
- contrib/registry/etcd/registry.go
- contrib/registry/eureka/register.go
- contrib/registry/zookeeper/register.go
- transport/grpc/balancer.go
> style: kratos interface check

- cmd/kratos/internal/base/vcs_url.go
Synchronous standard library's `scpSyntaxRe` regexp 
https://github.com/golang/go/blob/master/src/cmd/go/internal/vcs/vcs.go#L256
> cleanup: update `scpSyntaxRe` regexp

- cmd/protoc-gen-go-http/http.go
Remove redundant escaping characters in regex
> cleanup: regex replace `\.` => `.`

- contrib/config/etcd/README.md
> docs(config/etcd): fix the missing step of Load

- selector/node/ewma/node.go
dial tcp 127.0.0.1:9000: connect: connection refused
dial tcp 127.0.0.1:9000: i/o timeout
> fix(selector/ewma): judge net error

- cmd/kratos/version.go
- cmd/protoc-gen-go-errors/version.go
- cmd/protoc-gen-go-http/version.go
- contrib/encoding/msgpack/go.mod
- contrib/log/aliyun/go.mod
- contrib/log/fluent/go.mod
- contrib/log/logrus/go.mod
- contrib/log/tencent/go.mod
- contrib/log/zap/go.mod
- contrib/metrics/datadog/go.mod
- contrib/metrics/prometheus/go.mod
- contrib/opensergo/go.mod
- contrib/registry/consul/go.mod
- contrib/registry/discovery/go.mod
- contrib/registry/etcd/go.mod
- contrib/registry/kubernetes/go.mod
- contrib/registry/nacos/go.mod
- contrib/registry/polaris/go.mod
- contrib/registry/zookeeper/go.mod
- version.go
> deps: upgrade kratos version to v2.5.2

- contrib/config/apollo/README.md
- contrib/config/apollo/apollo.go
- contrib/config/apollo/watcher.go
- contrib/config/consul/README.md
- contrib/config/etcd/README.md
- contrib/config/kubernetes/config_test.go
- contrib/config/nacos/README.md
- contrib/config/nacos/go.mod
- contrib/config/polaris/README.md
- contrib/config/polaris/config.go
- contrib/config/polaris/watcher.go
> style(contrib/config): modify code style and wrong word

- selector/p2c/p2c_test.go
> typo: correct var name

- cmd/kratos/version.go
- cmd/protoc-gen-go-errors/version.go
- cmd/protoc-gen-go-http/version.go
- contrib/encoding/msgpack/go.mod
- contrib/log/aliyun/go.mod
- contrib/log/fluent/go.mod
- contrib/log/logrus/go.mod
- contrib/log/tencent/go.mod
- contrib/log/zap/go.mod
- contrib/metrics/datadog/go.mod
- contrib/metrics/prometheus/go.mod
- contrib/opensergo/go.mod
- contrib/registry/consul/go.mod
- contrib/registry/discovery/go.mod
- contrib/registry/etcd/go.mod
- contrib/registry/kubernetes/go.mod
- contrib/registry/nacos/go.mod
- contrib/registry/polaris/go.mod
- contrib/registry/zookeeper/go.mod
- version.go
> deps: upgrade kratos version to v2.5.3

- cmd/kratos/internal/base/mod_test.go
> chore(cmd): use t.Cleanup

- contrib/config/apollo/apollo.go
- contrib/config/apollo/apollo_test.go
- contrib/config/apollo/watcher.go
> fix[config]: fix codec NPE as parsing format wrongly, fix #2517

- encoding/form/form_test.go
- encoding/form/proto_encode.go
- encoding/form/proto_encode_test.go
- encoding/form/well_known_types_test.go
- encoding/proto/proto.go
add test and fix code style
part of #2354
> test(encoding/form/encode): add test and fix code style

- contrib/registry/consul/client.go
- contrib/registry/consul/registry.go
> feat: consul registry support get services from multiple datacenters

- cmd/kratos/internal/project/add.go
- cmd/kratos/internal/project/project.go
- cmd/kratos/internal/project/project_linux_test.go
- cmd/kratos/internal/project/project_test.go
- cmd/kratos/internal/project/project_windows_test.go
add test  and fixed repeat project name  in path
> Feat project create with dir name add test

- Makefile
i support makefile make install on windows environment.
> feat: support for windows make install

- contrib/registry/consul/registry.go
- contrib/registry/consul/registry_test.go
- contrib/registry/consul/watcher.go
#2549
- Return err if ctx is done
- Add select for goroutine exit
- Add a timeout option for get servers
- Optimize some codes
> fix(consul):return err if ctx is done

- contrib/registry/etcd/watcher.go
> fix(contrib/registry/etcd): rewatch when error occur

- transport/http/binding/encode_test.go
> chore(transport): fix the test name

- cmd/kratos/internal/project/project.go
fix issue https://github.com/go-kratos/kratos/issues/2609
> fix:project creation `--nomod`

- README.md
Update the link of go-zero in readme.
> chore: update go-zero link in readme

- middleware/recovery/recovery.go
- middleware/recovery/recovery_test.go
clean up deprecated code
NONE
NONE
> chore: clean up deprecated code

- .github/workflows/go.yml
> chore(ci): update go.yaml support golang 1.20

- contrib/registry/consul/client.go
- contrib/registry/consul/registry_test.go
> fix: do not re register after service logout

- contrib/log/zap/zap.go
> feat(log): update zap interface

- contrib/log/zap/zap.go
- transport/http/codec.go
> chore: replace deprecated method

- contrib/registry/eureka/client.go
- contrib/registry/eureka/eureka.go
> fix(contrib): fix eureka server load too high  (#2545)

- selector/filter/version.go
> fix nodes Version append func

- cmd/kratos/internal/proto/add/add.go
> fix: cmd `proto add` nil pointer

- transport/grpc/client.go
> feat: support load balance for streaming connection creation

- contrib/registry/eureka/watcher.go
- contrib/registry/servicecomb/registry.go
modify contrib registry eureka watcher as *watcher, defer ticker stop
> fix: fix contrib registry eureka watcher as *watcher

- cmd/kratos/version.go
- cmd/protoc-gen-go-errors/version.go
- cmd/protoc-gen-go-http/version.go
- contrib/encoding/msgpack/go.mod
- contrib/log/aliyun/go.mod
- contrib/log/fluent/go.mod
- contrib/log/logrus/go.mod
- contrib/log/tencent/go.mod
- contrib/log/zap/go.mod
- contrib/metrics/datadog/go.mod
- contrib/metrics/prometheus/go.mod
- contrib/opensergo/go.mod
- contrib/polaris/go.mod
- contrib/registry/consul/go.mod
- contrib/registry/discovery/go.mod
- contrib/registry/etcd/go.mod
- contrib/registry/kubernetes/go.mod
- contrib/registry/nacos/go.mod
- contrib/registry/polaris/go.mod
- contrib/registry/zookeeper/go.mod
- version.go
> deps: upgrade kratos version to v2.6.1

- cmd/kratos/internal/proto/server/server.go
> fix: correct message of CmdServer

- SECURITY.md
- selector/node/ewma/node.go
> fix: markdown form format

- Makefile
- transport/http/client_test.go
- transport/http/codec_test.go
> fix: remove repeat `net/http` package

- transport/grpc/client.go
- transport/grpc/resolver/discovery/builder.go
- transport/grpc/resolver/discovery/builder_test.go
- transport/grpc/resolver/discovery/resolver.go
> fix(grpc/balancer): fix the problem that the watch log cannot be closed

- cmd/kratos/internal/project/new.go
- cmd/kratos/internal/proto/client/client.go
- cmd/kratos/internal/proto/proto.go
- cmd/kratos/internal/upgrade/upgrade.go
- cmd/kratos/main.go
> fix(cmd): format import

- cmd/kratos/internal/base/path.go
- cmd/kratos/internal/base/repo.go
- cmd/kratos/internal/project/new.go
> fix(cmd/kratos/internal/base/repo.go): missing error

- .github/stable.yml
- .github/workflows/issue-translator.yml
> feat: issue translate and stable bot

- middleware/auth/jwt/jwt.go
returned by external dependencies, i.e.: KeyFunc
> feat: jwt KeyFunc external  return

- transport/http/server.go
Walks the router:
```go
engine := bm.Default()
srv := http.NewServer()
srv.WalkHandle(engine.HandleHTTP)
```
> feat(transport/http): add walk http handler

- cmd/kratos/version.go
- cmd/protoc-gen-go-errors/version.go
- cmd/protoc-gen-go-http/version.go
- contrib/config/apollo/go.mod
- contrib/config/consul/go.mod
- contrib/config/etcd/go.mod
- contrib/config/kubernetes/go.mod
- contrib/config/nacos/go.mod
- contrib/config/polaris/go.mod
- contrib/encoding/msgpack/go.mod
- contrib/log/aliyun/go.mod
- contrib/log/fluent/go.mod
- contrib/log/logrus/go.mod
- contrib/log/tencent/go.mod
- contrib/log/zap/go.mod
- contrib/log/zerolog/go.mod
- contrib/log/zerolog/go.sum
- contrib/metrics/datadog/go.mod
- contrib/metrics/prometheus/go.mod
- contrib/opensergo/go.mod
- contrib/polaris/go.mod
- contrib/registry/consul/go.mod
- contrib/registry/discovery/go.mod
- contrib/registry/etcd/go.mod
- contrib/registry/eureka/go.mod
- contrib/registry/kubernetes/go.mod
- contrib/registry/nacos/go.mod
- contrib/registry/polaris/go.mod
- contrib/registry/zookeeper/go.mod
- version.go
> deps: upgrade kratos version to v2.7.0

- .github/workflows/go.yml
> support 1.21.x

- app.go
- contrib/config/consul/config.go
- contrib/registry/eureka/eureka.go
- contrib/registry/eureka/register.go
- contrib/registry/polaris/registry.go
- selector/filter/version.go
- transport/grpc/client.go
- transport/grpc/resolver/direct/builder.go
- transport/grpc/resolver/discovery/builder_test.go
- transport/http/client.go
- transport/http/resolver.go
- transport/http/server.go
fix some words 
format
add a test
> chore:chore update

- contrib/config/consul/watcher.go
> feat: support consul sign config change

- cmd/kratos/version.go
- cmd/protoc-gen-go-errors/version.go
- cmd/protoc-gen-go-http/version.go
- contrib/config/apollo/go.mod
- contrib/config/consul/go.mod
- contrib/config/etcd/go.mod
- contrib/config/kubernetes/go.mod
- contrib/config/nacos/go.mod
- contrib/config/polaris/go.mod
- contrib/encoding/msgpack/go.mod
- contrib/log/aliyun/go.mod
- contrib/log/fluent/go.mod
- contrib/log/logrus/go.mod
- contrib/log/tencent/go.mod
- contrib/log/zap/go.mod
- contrib/log/zerolog/go.mod
- contrib/metrics/datadog/go.mod
- contrib/metrics/prometheus/go.mod
- contrib/opensergo/go.mod
- contrib/polaris/go.mod
- contrib/registry/consul/go.mod
- contrib/registry/discovery/go.mod
- contrib/registry/etcd/go.mod
- contrib/registry/eureka/go.mod
- contrib/registry/kubernetes/go.mod
- contrib/registry/nacos/go.mod
- contrib/registry/polaris/go.mod
- contrib/registry/zookeeper/go.mod
- version.go
> deps: upgrade kratos version to v2.7.3

- config/config.go
- config/config_test.go
- config/reader_test.go
- contrib/config/apollo/go.mod
- contrib/config/apollo/go.sum
- contrib/config/consul/go.mod
- contrib/config/consul/go.sum
- contrib/config/etcd/go.mod
- contrib/config/etcd/go.sum
- contrib/config/kubernetes/go.mod
- contrib/config/kubernetes/go.sum
- contrib/config/nacos/go.mod
- contrib/config/nacos/go.sum
- contrib/config/polaris/go.mod
- contrib/config/polaris/go.sum
- contrib/polaris/go.mod
- contrib/polaris/go.sum
- contrib/registry/kubernetes/go.mod
- contrib/registry/kubernetes/go.sum
- go.mod
- go.sum
Change "github.com/imdario/mergo v0.3.16" to "dario.cat/mergo v1.0.0" because mergo has changed its name [link](https://github.com/darccio/mergo?tab=readme-ov-file#important-notes).
resolves: #3149
Please note "contrib/config/kubernetes/go.mod" and "contrib/registry/kubernetes/go.mod". The version of "github.com/imdario/mergo" was downgrade to v0.3.6 cause the underline dependency "k8s.io/client-go/tools/clientcmd" uses this version.
> dep: change library name of mergo #3149

- middleware/metrics/metrics.go
if requests and seconds are nil, return directory
> chore(middleware/metrics): if requests and seconds are nil, return directory

- transport/http/client.go
> The issue that the response header is not assigned a value is fixed

- contrib/config/polaris/config.go
- contrib/errortracker/sentry/sentry.go
- contrib/registry/discovery/discovery.go
- contrib/registry/zookeeper/register.go
> chroe: chore update

- transport/http/client_test.go
- transport/http/server_test.go
> test: remove non-existent test methods

- middleware/logging/logging.go
- middleware/metrics/metrics.go
> fix: resolve the issue of metrics and logging code default to zero

- cmd/kratos/version.go
- cmd/protoc-gen-go-errors/version.go
- cmd/protoc-gen-go-http/version.go
- contrib/config/apollo/go.mod
- contrib/config/consul/go.mod
- contrib/config/etcd/go.mod
- contrib/config/kubernetes/go.mod
- contrib/config/nacos/go.mod
- contrib/config/polaris/go.mod
- contrib/encoding/msgpack/go.mod
- contrib/errortracker/sentry/go.mod
- contrib/log/aliyun/go.mod
- contrib/log/fluent/go.mod
- contrib/log/logrus/go.mod
- contrib/log/tencent/go.mod
- contrib/log/zap/go.mod
- contrib/log/zerolog/go.mod
- contrib/opensergo/go.mod
- contrib/polaris/go.mod
- contrib/registry/consul/go.mod
- contrib/registry/discovery/go.mod
- contrib/registry/etcd/go.mod
- contrib/registry/eureka/go.mod
- contrib/registry/kubernetes/go.mod
- contrib/registry/nacos/go.mod
- contrib/registry/polaris/go.mod
- contrib/registry/servicecomb/go.mod
- contrib/registry/zookeeper/go.mod
- version.go
- feat: create build Group in changelog generate. (#3448)
- fix: unit test Recycle watch resolver tick goroutine (#3449)
- fix: resolve the issue of metrics and logging code default to zero (#3447)
- build(deps): bump golang.org/x/sync in /contrib/registry/zookeeper (#3387)
> deps: upgrade kratos version to v2.8.2

- contrib/registry/nacos/registry.go
- contrib/registry/nacos/registry_test.go
- Add support for reading weight information from metadata during service registration and discovery
- Update test cases to use non-local test server addresses
> feat(registry/nacos): support service discovery weight

- README_zh.md
> docs: optimize readme zh docs

- go.mod
- go.sum
Ref:https://nvd.nist.gov/vuln/detail/CVE-2025-30204
> deps:deps CVE-2025-30204 about golang-jwt

- contrib/transport/mcp/README.md
- contrib/transport/mcp/server.go
```go
// Health is a health check handler.
func Health(next http.Handler) http.Handler {
return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
if r.URL.Path == "/health/ready" {
w.WriteHeader(http.StatusOK)
return
}
next.ServeHTTP(w, r)
})
}
srv := mcp.NewServer("Discovery", "v1.0.0",
mcp.Address(":8000"),
mcp.Middleware(Health),
)
```
> add mcp middleware

- contrib/middleware/validate/validate.go
- contrib/polaris/ratelimit.go
- errors/errors.go
- middleware/ratelimit/ratelimit.go
- middleware/validate/validate.go
- transport/http/binding/bind.go
- transport/http/binding/bind_test.go
- transport/http/codec.go
fix #3647 
My fault, really sorry
> Revert "refactor: replace repeated error reasons with constants"

- Makefile
solve syntax error when execute make command.
Fixes #3681
> fix: solve have syntax error when execute make command.

- contrib/polaris/registry.go
- contrib/polaris/router.go
- contrib/registry/consul/client.go
- contrib/registry/kubernetes/registry.go
- contrib/registry/nacos/registry.go
- contrib/registry/nacos/watcher.go
- contrib/registry/polaris/registry.go
```fmt.Sprintf("%s:%d", host, port)``` will not work with IPv6; instead it suggests using [net.JoinHostPort](https://tip.golang.org/pkg/net#JoinHostPort).
> *: use net.JoinHostPort to improve IPv6 compatible
